
<?php

/*$_currentTimeStamp = Mage::getSingleton('core/date')->timestamp(time());
$_productId = null;

$_disabledDays = ITwebexperts_Payperrentals_Helper_Data::getDisabledDays($_productId);

$_paddingDays = ITwebexperts_Payperrentals_Helper_Data::getProductPaddingDays($_productId, $_currentTimeStamp);
$_paddingDays = ITwebexperts_Payperrentals_Helper_Data::toFormattedDateArray($_paddingDays);

$_blockedDates = ITwebexperts_Payperrentals_Helper_Data::getDisabledDates($_productId);
$_blockedDates = ITwebexperts_Payperrentals_Helper_Data::toFormattedDateArray($_blockedDates);
//dayShortNames = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];
    //disabledDatesPadding = [<?php echo implode(',', $_paddingDays);?>];
    //blockedDates = [<?php echo implode(',', $_blockedDates);?>];
    //disabledDays = ["<?php echo implode('","', $_disabledDays);?>"];
*/
?>
<script type="text/javascript">
    //<![CDATA[
    function showLateFeePopup(id,orderid){
        win = new Window({
            closable:true,
            resizable:false,
            draggable:true,
            className:'magento',
            windowClassName:'popup-window',
            title:'Create Late Fee',
            top:50,
            width:300,
            height:150,
            zIndex:1000,
            recenterAuto:false,
            hideEffect:Element.hide,
            showEffect:Element.show,
            destroyOnClose: true,
            onClose: function(){
                $('popup_form_policy').setStyle({
                    display:'none'
                });
            },
            id:'browser_window'
        });
        win.setContent(id, false, false);
        win.showCenter();
        $('orderid').value = orderid;
    }
    function hidediv(){
        $('popup_form_policy').setStyle({
            display:'none'
        });
    }
    $jppr(document).ready(function() {
        $jppr.ajax({
            url: "<?php echo ITwebexperts_Payperrentals_Helper_Html::getDatepickerLocalePath();?>",
            dataType: "script",
            cache: true
        }).done(function () {
            $jppr.datepicker.regional['<?php echo ITwebexperts_Payperrentals_Helper_Html::getLocaleCodeForHtml();?>'];
        });
        $jppr.ajax({
            url: "<?php echo ITwebexperts_Payperrentals_Helper_Html::getDatetimepickerLocalePath();?>",
            dataType: "script",
            cache: true
        }).done(function () {
            $jppr.timepicker.regional['<?php echo ITwebexperts_Payperrentals_Helper_Html::getLocaleCodeForHtml();?>'];
        });

        $jppr(".late_date").datetimepicker({
            showOn: "both",
            buttonImage: "<?php echo ITwebexperts_Payperrentals_Helper_Html::getCalendarPopupImage(); ?>",
            buttonImageOnly: true,
            buttonText: "Select date",
            timeFormat: 'HH:mm:ss',
            stepHour: 1,
            stepMinute: 30,
            showSecond: false,
            showButtonPanel: false,
            /*beforeShowDay: function (dateObj) {
                dateObj.setHours(0, 0, 0, 0);
                var dateFormatted = $jppr.datepicker.formatDate('yy-m-d', dateObj);

                if ($jppr.inArray(dayShortNames[dateObj.getDay()], disabledDays) > -1) {
                    return [false, 'ui-datepicker-disabled manualadded disabledday', '<?php echo $this->__('Not Available'); ?>'];
                }
                else if ($jppr.inArray(dateFormatted, disabledDatesPadding) > -1) {
                    return [false, 'ui-datepicker-disabled manualadded disabledpadding', '<?php echo $this->__('Not Available'); ?>'];
                } else if ($jppr.inArray(dateFormatted, blockedDates) > -1) {
                    return [false, 'ui-datepicker-disabled manualadded blockeddate', '<?php echo $this->__('Not Available'); ?>'];
                }
                return [true, 'availabledate', '<?php echo $this->__('Available'); ?>'];
            }*/
        });
    });
</script>

<div id="popup_form_policy" style="display:none;">

    <form name="latefeeform" action="<?php echo Mage::helper("adminhtml")->getUrl('payperrentals_admin/adminhtml_latefee'); ?>">
    <input id="orderid" name="orderid" type="hidden" value="33">

        <!--Charge custom price: <input type="text" name="custom_price"/><br/>-->
        Late Return Date: <input class="late_date" class="input-text" type="datetime" name="late_date"> <br />
        <br /><br /><button type="submit" class="button" title="Submit"><span><span>Submit</span></span></button>
    </form>

</div>