<?php /** @var $this Mage_Checkout_Block_Onepage_Shipping_Method_Available */ ?>
<?php $_shippingRateGroups = $this->getShippingRates(); ?>
<?php if (!$_shippingRateGroups): ?>
    <p><?php echo $this->__('Sorry, no quotes are available for this order at this time.') ?></p>
<?php else: ?>
    <dl class="sp-methods">
        <?php $shippingCodePrice = array(); ?>
        <?php /** Don't show other carriers if method selected by rshipping */ ?>
        <?php $_rentalShipping = (Mage::getSingleton('checkout/session')->hasData('rental_shipping')) ? Mage::getSingleton('checkout/session')->getData('rental_shipping') : null ?>
        <?php $_carrierCodeAr = array(); ?>
        <?php $_ratesCodeAr = array(); ?>
        <?php foreach ($_shippingRateGroups as $_code => $_ratesCollection): ?>
            <?php $_carrierCodeAr[] = $_code; ?>
            <?php foreach ($_ratesCollection as $_rateItem): ?>
                <?php $_ratesCodeAr[] = $_rateItem->getCode(); ?>
            <?php endforeach; ?>
        <?php endforeach; ?>
        <?php $_sole = count($_shippingRateGroups) == 1;
        foreach ($_shippingRateGroups as $code => $_rates): ?>
            <?php if (!is_null($_rentalShipping) && array_key_exists('carrier', $_rentalShipping) && array_search($_rentalShipping['carrier'], $_carrierCodeAr) !== false && $code != $_rentalShipping['carrier']) continue; ?>
            <dt><?php echo $this->escapeHtml($this->getCarrierName($code)) ?></dt>
            <dd>
                <ul>
                    <?php $_sole = $_sole && count($_rates) == 1;
                    foreach ($_rates as $_rate): ?>
                        <?php if (!is_null($_rentalShipping) && array_key_exists('method', $_rentalShipping) && array_search($_rentalShipping['method'], $_ratesCodeAr) !== false && $_rate->getCode() != $_rentalShipping['method']) continue; ?>
                        <?php $_rentalShippingMethod = Mage::getModel('rshipping/rshipping')->load($_rentalShipping['method'], 'shipping_method') ?>
                        <?php if ($_rentalShippingMethod->getId() && $_rentalShippingMethod->getUseCustomShippingAmount() && $_rentalShippingMethod->getShippingAmount()): ?>
                            <?php $_shippingAmount = $this->getQuote()->getStore()->convertPrice($_rentalShippingMethod->getShippingAmount()) ?>
                        <?php else: ?>
                            <?php $_shippingAmount = (float)$_rate->getPrice() ?>
                        <?php endif; ?>
                        <?php $shippingCodePrice[] = "'" . $_rate->getCode() . "':" . $_shippingAmount; ?>
                        <li>
                            <?php if ($_rate->getErrorMessage()): ?>
                                <ul class="messages">
                                    <li class="error-msg">
                                        <ul>
                                            <li><?php echo $this->escapeHtml($_rate->getErrorMessage()) ?></li>
                                        </ul>
                                    </li>
                                </ul>
                            <?php else: ?>
                                <?php if ($_sole) : ?>
                                    <span class="no-display"><input name="shipping_method" type="radio" value="<?php echo $_rate->getCode() ?>" id="s_method_<?php echo $_rate->getCode() ?>" checked="checked"/></span>
                                <?php else: ?>
                                <input name="shipping_method" type="radio" value="<?php echo $_rate->getCode() ?>" id="s_method_<?php echo $_rate->getCode() ?>"<?php if ($_rate->getCode() === $this->getAddressShippingMethod()) echo ' checked="checked"' ?> class="radio"/>

                                <?php if ($_rate->getCode() === $this->getAddressShippingMethod()): ?>
                                    <script type="text/javascript">
                                        //<![CDATA[
                                        lastPrice = <?php echo $_shippingAmount; ?>;
                                        //]]>
                                    </script>
                                <?php endif; ?>

                                <?php endif; ?>
                                <label for="s_method_<?php echo $_rate->getCode() ?>"><?php echo $this->escapeHtml($_rate->getMethodTitle()) ?>
                                    <?php $_excl = $this->getShippingPrice($_shippingAmount, $this->helper('tax')->displayShippingPriceIncludingTax()); ?>
                                    <?php $_incl = $this->getShippingPrice($_shippingAmount, true); ?>
                                    <?php echo $_excl; ?>
                                    <?php if ($this->helper('tax')->displayShippingBothPrices() && $_incl != $_excl): ?>
                                        (<?php echo $this->__('Incl. Tax'); ?> <?php echo $_incl; ?>)
                                    <?php endif; ?>
                                </label>
                            <?php endif ?>
                        </li>
                    <?php endforeach; ?>
                </ul>
            </dd>
        <?php endforeach; ?>
    </dl>
    <script type="text/javascript">
        //<![CDATA[
        <?php if (!empty($shippingCodePrice)): ?>
        var shippingCodePrice = {<?php echo implode(',',$shippingCodePrice); ?>};
        <?php endif; ?>

        $$('input[type="radio"][name="shipping_method"]').each(function (el) {
            Event.observe(el, 'click', function () {
                if (el.checked == true) {
                    var getShippingCode = el.getValue();
                    <?php if (!empty($shippingCodePrice)): ?>
                    var newPrice = shippingCodePrice[getShippingCode];
                    if (!lastPrice) {
                        lastPrice = newPrice;
                        quoteBaseGrandTotal += newPrice;
                    }
                    if (newPrice != lastPrice) {
                        quoteBaseGrandTotal += (newPrice - lastPrice);
                        lastPrice = newPrice;
                    }
                    <?php endif; ?>
                    checkQuoteBaseGrandTotal = quoteBaseGrandTotal;
                    return false;
                }
            });
        });
        //]]>
    </script>
<?php endif; ?>
