<?php
/**
 * For compatibility reason with any template all the js files are loaded with the calendar.
 * This will ensure that the calendar will work with any template without any problem
 *
 */
?>
<script type="text/javascript" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS) .'itwebexperts_payperrentals/datepick/date.js'; ?>"></script>
<script type="text/javascript" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS) . 'itwebexperts_payperrentals/jquery/jquery-1.11.1.min.js'; ?>"></script>

<script type="text/javascript">
    if(typeof $jppr == 'undefined') {$jppr = jQuery.noConflict();}
</script>

<script type="text/javascript" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS) .'itwebexperts_payperrentals/datepick/jquery.formatDateTime.js'; ?>"></script>
<link rel="stylesheet" type="text/css" href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN) . 'frontend/base/default/itwebexperts_payperrentals/datepick/default/jquery-ui.theme.css'; ?>" media="all"/>
<?php if (Mage::helper('payperrentals/config')->getThemeStyle(Mage::app()->getStore()->getId()) != ITwebexperts_Payperrentals_Model_Source_Themestyle::DEFAULT_STYLE): ?>
    <link rel="stylesheet" type="text/css" href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN) . 'frontend/base/default/itwebexperts_payperrentals/datepick/default/themeroller-standard.css'; ?>" media="all"/>
    <link rel="stylesheet" type="text/css" href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN) . 'frontend/base/default/itwebexperts_payperrentals/datepick/'. Mage::helper('payperrentals/config')->getThemeStyle(Mage::app()->getStore()->getId()).'/jquery-ui.theme.css'; ?>" media="all"/>
<?php endif; ?>
<script type="text/javascript" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS) . 'itwebexperts_payperrentals/datepick/jquery.datepick.js'; ?>"></script>

<?php if (!Mage::app()->getStore()->isAdmin()): ?>
    <script type="text/javascript" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS) . 'mage/adminhtml/events.js'; ?>"></script>
<?php else: ?>
    <script type="text/javascript" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS) .'itwebexperts_payperrentals/autocomplete/jquery-autocomplete.js'; ?>"></script>
    <link rel="stylesheet" href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS) .'itwebexperts_payperrentals/autocomplete/jquery-autocomplete.css'; ?>" />
<?php endif; ?>

<?php if(!$_useFlicker){
    $_langCode = $localeCode;
}else{
    $_langCode = 'flick';
}
?>
<script type="text/javascript" src="<?php
    echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS) . 'itwebexperts_payperrentals/datepick/locale/jquery.datepick-'. $_langCode;?>.js">
</script>


<script type="text/javascript">
    qtyDefaultArr = [];
    partiallyBooked = [];
    bookedDates = [<?php echo implode(',', $_booked);?>];
    autoSelectFlag = false;
     <?php /** @ $_configHelper ITwebexperts_Payperrentals_Helper_Config */ ?>
    useTimes = <?php echo $_useTimes;?>;
    isDisabled = <?php echo ($_isDisabled == true)?'true':'false'; ?>;
    autoSelectEndDate = <?php echo ($_autoSelectEndDate == true)?'true':'false'; ?>;
    selectedToEndPeriod = '<?php echo (ITwebexperts_Payperrentals_Helper_Config::isAddStartDate()?($_selectedToEndPeriod - 1):$_selectedToEndPeriod);?>';
    selectedToStartPeriod = '<?php echo $_selectedToStartPeriod;?>';
    startDateHtml = '<?php echo $this->__('Selected Start Date: ');?>';
    endDateHtml = '<?php echo $this->__('Selected End Date: ');?>';
    minRentalPeriodMessage = '<?php echo $_minRentalMessage;?>';
    betweenErrorMessage = '<?php echo $this->__('There are Dates in between your selected period which do not have available inventory');?>';
    pleaseSelectMessage = '<?php echo $this->__('Please select start and end dates');?>';
    noPriceMessage = '<?php echo $this->__('No price is available for these rental periods');?>';
    chooseOptionsForPrice = '<?php echo $this->__('Please choose product options for price');?>';
    noQtyMessage = '<?php echo $this->__('No quantity available for these rental periods');?>';
    maxRentalPeriodMessage = '<?php echo $_maxRentalMessage; ?>';
    isDisabledByTimes = false;
    bprice = 0;
    dateFormat = '<?php echo $_datestr; ?>';
    useGlobals = <?php echo ($_useGlobalDates?'true':'false')?>;
    useCalendarOnProductInfo = <?php echo ( ITwebexperts_Payperrentals_Helper_Config::showCalendarOnProductInfo()?'true':'false')?>;
    isProduct = <?php echo ($this->getProduct()?'true':'false')?>;
    addStartingDateNumber = <?php echo (ITwebexperts_Payperrentals_Helper_Config::isAddStartDate() ? '1' : '0');?>;
    addStartingDatePeriod = <?php echo (ITwebexperts_Payperrentals_Helper_Config::isAddStartDate() ? '86400000' : '0');?>;
    disabledStartWeekDays = [];
    disabledEndWeekDays = [];
    minRentalPeriod = <?php echo ($_minRentalPeriod*1000);?>;
     dayShortName = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];
     disabledDaysStart = [<?php echo implode(',', $_disabledDaysStart);?>];
     disabledDaysEnd = [<?php echo implode(',', $_disabledDaysEnd);?>];
     ignoreTurnoverDay = [<?php echo implode(',', $_ignoreTurnoverDay);?>];
     disabledDatesPadding = [<?php echo implode(',', $_paddingDays);?>];
     blockedDates = [<?php echo implode(',', $_blockedDates);?>];
     disabledDays = ["<?php echo implode('","', $_disabledDays);?>"];
     maxRentalPeriod = <?php echo ($_maxRentalPeriod*1000);?>;
     disabledWithMessage = <?php echo $_disableWithMessage;?>;
     disabledMessage = '<?php echo $_disabledMessage;?>';
     disabledMessageTurnovers = '<?php  echo $this->__('Date is disabled because turnover days');?>';
     betweenMessage = '<?php echo $_betweenMessage; ?>';
     turnoverTimeBefore = <?php echo $_turnoverTimeBefore; ?>;
     turnoverTimeAfter = <?php echo $_turnoverTimeAfter; ?>;
     minQty = 10000;
     startArray = [<?php echo implode(',', $_timeBooked);?>];
     bookedTimesArr = [<?php echo implode(',', $_timeBookedDate);?>];
</script>


