<?php
/**
 * Mojo Creative & Technical Solutions LLC
 *
 * @category   GetSomeMojo
 * @package    GetSomeMojo_Bundledmojo
 * @copyright  Copyright (c) 2011-2013 Mojo Creative & Technical Solutions LLC (http://GetSome.MojoMage.com)
 * @license    http://getsome.mojomage.com/license/
 * @author     Mojo Creative & Technical Solutions LLC <info@MojoMage.com>
 *
 * @var $this Mage_Bundle_Block_Catalog_Product_View_Type_Bundle_Option_Radio
 */
?>
<?php $_option     = $this->getOption() ?>
<?php $_selections = $_option->getSelections() ?>
<?php $_default    = $_option->getDefaultSelection() ?>
<?php $_showSingle = (count($_selections) == 1 && $_option->getRequired()) ?>
<div id="title-<?php echo $_option->getId() ?>">
    <dt>
        <label<?php if ($_option->getRequired()) echo ' class="required"' ?>><?php echo $this->htmlEscape($_option->getTitle()) ?><?php if ($_option->getRequired()) echo '<em>*</em>' ?></label>
    </dt>
    <dd<?php if ($_option->decoratedIsLast) echo ' class="last"'; ?>>
        <div class="input-box">
        <?php if (count($_selections) == 1 && $_option->getRequired()): ?>
            <?php //echo $this->getSelectionTitlePrice($_selections[0]); ?>
            <input type="hidden" name="bundle_option[<?php echo $_option->getId(); ?>]" value="<?php echo $_selections[0]->getSelectionId(); ?>" id="bundle-option-<?php echo $_option->getId(); ?>-<?php echo $_selections[0]->getSelectionId(); ?>" />
        <?php elseif (count($_selections) == 1 && !$_option->getRequired()): ?>
            <?php //if (!$_option->getRequired()) { ?>
            <ul class="options-list">
                <li>
                    <input type="radio" onclick="bundle.changeSelection(this)" class="radio" id="bundle-option-<?php echo $_option->getId(); ?>" name="bundle_option[<?php echo $_option->getId(); ?>]"<?php echo ($_default && $_default->isSalable())?'':' checked="checked" ' ?> value=""/>
                    <span class="label">
                        <label for="bundle-option-<?php echo $_option->getId(); ?>">
                            <?php echo $this->__('None'); ?>
                        </label>
                    </span>
                </li>
            </ul>
        <?php endif;//} ?>
            <!-- Begin Show Bundled Products -->
            <?php foreach ($_selections as $_selection): ?>
            <?php $_productName = str_replace('"', '&nbsp;', $_selection->getName()); ?>
            <div<?php if ($this->getYeaH4yeaH() && $this->getYeaH4radio()) echo ' class="bundledmojo_wrapper-' . $_selection->getSelectionId() . '" id="bundledmojo_wrapper"'; ?>>
                <?php if ($this->getBaseImage() || $this->getWishlist() || $this->getCompare()): ?>
                <!-- The Following DIV dictates the float position of the Image and Layout -->
                <div style="float:<?php if (!strpos($this->helper('catalog/image')->init($_selection, 'small_image'), 'placeholder')) { echo $this->getImageFloat(); } else { echo 'right'; } ?>;" class="bundledmojo_image_wrapper">
                    <!-- Thumbnail Image -->
                    <?php if ($this->getBaseImage() && !strpos($this->helper('catalog/image')->init($_selection, 'small_image'), 'placeholder')): ?>
                    <div class="bundledmojo_image" style="padding-<?php echo ($this->getImageFloat() == 'right' ? 'left' : 'right'); ?>:10px; padding-top: 5px;">
                        <a href="<?php echo $this->helper('catalog/image')->init($_selection, 'small_image')->constrainOnly(TRUE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize($this->getZoomWidth()); ?>" class="mojoRadioZoom" title="<?php echo $_productName; ?>" onclick="return false">
                            <img src="<?php echo $this->helper('catalog/image')->init($_selection, 'small_image')->constrainOnly(TRUE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize($this->getThumbSize()); ?>" alt="<?php echo $_productName; ?>" class="resize-<?php echo $_selection->getSelectionId(); ?> resize" id="imageZoom_toggle-<?php echo $_selection->getSelectionId(); ?>" />
                        </a>
                    </div>
                    <!-- End Thumbnail Image -->
                    <?php endif; // $this->getBaseImage() ?>
                    <!-- If Wishlist or Add to Compare is Enabled Display Link(s) -->
                    <?php if ($this->getWishlist() || $this->getCompare()): ?>
                    <div style="<?php echo $this->getImageFloat() . ": 0; text-align:" . $this->getImageFloat() . ";"; ?>" class="mojowishcompare_wrapper imageZoom_toggle-<?php echo $_selection->getSelectionId(); ?>">
                        <?php if ($this->helper('wishlist')->isAllow() && $this->getWishlist()) { ?>
                        <a href="<?php echo $this->helper('wishlist')->getAddUrl($_selection); ?>" class="link-compare">
                            <?php echo $this->__('Add To Wishlist'); ?>
                        </a>
                        <?php } ?>
                        <?php if ($this->helper('wishlist')->isAllow() && $this->getWishlist() && $this->getCompare()) { ?>
                        <br />
                        <?php } ?>
                        <?php if ($this->getCompare()) { ?>
                        <a href="<?php echo $this->helper('catalog/product_compare')->getAddUrl($_selection); ?>" class="link-compare">
                            <?php echo $this->__('Add to Compare'); ?>
                        </a>
                        <?php } ?>
                    </div>
                    <?php endif; // $this->getWishlist() || $this->getCompare() ?>
                <!-- End .bundledmojo_image_wrapper -->
                </div>
                <?php endif; // $this->getBaseImage() || $this->getWishlist() || $this->getCompare() ?>
                <div<?php if ($this->getYeaH4yeaH() && $this->getYeaH4radio()) { echo ' id="bundledmojo_desc_wrapper"'; } ?> style="<?php if ($this->getImageFloat() == 'left') { echo $this->getImageFloat() . ": 175px;"; } else { echo "margin-right: 145px"; } ?>">
                    <!-- Begin Radio Button -->
                    <?php if (count($_selections) > 1): ?>
                    <input type="radio" onclick="bundle.changeSelection(this)" class="radio<?php echo $_option->getRequired()?' validate-one-required-by-name':''; ?>" id="bundle-option-<?php echo $_option->getId(); ?>-<?php echo $_selection->getSelectionId(); ?>" name="bundle_option[<?php echo $_option->getId(); ?>]"<?php echo ($_selection->getIsDefault() && $_selection->isSaleable())?' checked="checked" ':''; ?><?php echo !$_selection->isSaleable()?' disabled="disabled" ':''; ?>value="<?php echo $_selection->getSelectionId(); ?>" />
                    <?php endif; // count($_selections) == 1 && !$_option->getRequired() ?>
                    <span class="label">
                        <label for="bundle-option-<?php echo $_option->getId(); ?>-<?php echo $_selection->getSelectionId(); ?>">
                            <?php if ($this->getProdNameUrl()): ?>
                            <a href="<?php echo $this->htmlEscape($_selection->getProductUrl()); ?>" title="<?php echo $this->getName($_selection); ?>" target="_blank">
                                <?php if ($this->getProdPrice()): ?>
                                    <?php echo $this->getSelectionTitlePrice($_selection, false); ?>
                                <?php else: ?>
                                    <?php echo $_productName; ?>
                                <?php endif; ?>
                            </a>
                            <?php else: ?>
                                <?php if ($this->getProdPrice()): ?>
                                    <?php echo $this->getSelectionTitlePrice($_selection, false); ?>
                                <?php else: ?>
                                    <?php echo $_productName; ?>
                                <?php endif; ?>
                            <?php endif; // $this->getName($_selection) ?>
                        </label>
                    </span>
                    <!-- End  Radio Button -->
                    <?php /* @MOJO - Check if Bundled Mojo is Enabled and if it is Begin Product Description */ ?>
                    <?php if ($this->getYeaH4yeaH() && $this->getYeaH4radio()): ?>
                    <br />
                    <!-- Begin Product Description -->
                    <div>
                        <!-- Text To Display -->
                        <?php if ($this->getShortDescInit() == 0 && $this->getShortDesc()): ?>
                        <div id="<?php echo $_selection->getSelectionId(); ?>">
                            <a id="<?php echo $_selection->getSelectionId(); ?>" class="prodDescToggle">
                                <?php if ($this->getShortDescText()) echo $this->getShortDescText(); else echo $this->getShortDescTextDefault(); ?>
                            </a>
                        </div>
                        <?php endif; // $this->getShortDescInit() == 0 && $this->getShortDesc() ?>

                        <?php if ($this->getShortDesc()): ?>
                        <div class="<?php echo $_selection->getSelectionId(); ?> std" id="bundleDescUl"<?php if ($this->getShortDesc() && $this->getShortDescInit() == 0) echo ' style="display: none;"'; ?>>
                        <!-- Product Description -->
                        <?php $_productDesc = Mage::getSingleton('catalog/product')->load($_selection->getId()); ?>
                        <?php echo $_productDesc->getShortDescription(); ?>

                        </div>
                        <?php endif; // $this->getShortDesc() ?>
                    </div>
                    <!-- End Product Description -->
                    <?php endif; // $this->getYeaH4yeaH() && $this->getYeaH4radio() ?>
                    <?php if (count($_selections) == 1 && $_option->getRequired()): ?>
                    <?php echo $this->setValidationContainer('bundle-option-' . $_option->getId() . '-' . $_selections[0]->getSelectionId(), 'bundle-option-' . $_option->getId() . '-container'); ?>
                    <?php elseif (count($_selections) > 1 && $_option->getRequired()): ?>
                    <?php echo $this->setValidationContainer('bundle-option-' . $_option->getId() . '-' . $_selection->getSelectionId(), 'bundle-option-' . $_option->getId() . '-container'); ?>
                    <?php endif; // count($_selections) == 1 && $_option->getRequired() ?>
                <!-- End #bundledmojo_desc_wrapper -->
                </div>
            <!-- End #bundledmojo_wrapper -->
            </div>
            <?php if ($this->getBaseImage() && !strpos($this->helper('catalog/image')->init($_selection, 'small_image'), 'placeholder')): ?>
            <!-- Added for Bundled Mojo Layout -->
            <div style="clear: both;"></div>
            <?php endif; ?>
            <!-- End Show Bundled Products -->
        <?php endforeach; // $_selections as $_selection ?>
        <?php if (count($_selections) == 1 && $_option->getRequired()): ?>
        <div id="bundle-option-<?php echo $_selections[0]->getSelectionId(); ?>-container"></div>
        <?php else: ?>
        <div id="bundle-option-<?php echo $_option->getId(); ?>-container"></div>
        <?php endif; // count($_selections) == 1 && $_option->getRequired() ?>
        <?php //endif; // count($_selections) == 1 && $_option->getRequired() ?>
        </div>
        <div class="bundle-qty-container">
            <span class="qty-holder">
                <?php if ($_default) { ?>
                    <?php $_defaultQty = $_default->getSelectionQty() * 1; ?>
                    <?php $_canChangeQty = $_default->getSelectionCanChangeQty(); ?>
                <?php } else { ?>
                    <?php if (!$_showSingle) { ?>
                        <?php $_defaultQty = '0'; ?>
                        <?php $_canChangeQty = false; ?>
                    <?php } else { ?>
                        <?php $_defaultQty = $_selections[0]->getSelectionQty() * 1; ?>
                        <?php $_canChangeQty = $_selections[0]->getSelectionCanChangeQty(); ?>
                    <?php } ?>
                <?php } ?>
                <label for="bundle-option-<?php echo $_option->getId(); ?>-qty-input"><?php echo $this->__('Qty:'); ?>&nbsp;</label>
                <input onkeyup="bundle.changeOptionQty(this, event)" onblur="bundle.changeOptionQty(this, event)" <?php if (!$_canChangeQty) { echo ' disabled="disabled"'; } ?> id="bundle-option-<?php echo $_option->getId(); ?>-qty-input" class="input-text qty<?php if (!$_canChangeQty) { echo ' qty-disabled'; } ?>" type="text" name="bundle_option_qty[<?php echo $_option->getId(); ?>]" value="<?php echo $_defaultQty; ?>" />
            </span>
        </div>
    </dd>
</div>
<style type="text/css">
#mojoRadioZoom {
    position: absolute;
    border: <?php echo $this->getZoomBorderSize(); ?>px solid #<?php echo $this->getZoomBorderColor(); ?>;
    background: #<?php echo $this->getZoomBgColor(); ?>;
    padding: <?php echo $this->getZoomImagePadding(); ?>px;
    display: none;
    color: #<?php echo $this->getZoomFontColor(); ?>;
    z-index: 420;
}
</style>
<script type="text/javascript">
<?php if ($this->getShortDescInit() == 0): ?>
    <?php foreach ($_selections as $_selection): ?>
jQuery("#<?php echo $_selection->getSelectionId(); ?>").click(function () {
    jQuery(".<?php echo $_selection->getSelectionId(); ?>").slideToggle( 'slow', 'linear' );
});
    <?php endforeach; ?>
<?php endif; // $this->getShortDescInit() == 0 ?>
<?php if ($this->getImageZoom()): ?>
jQuery("a.mojoRadioZoom").hover(function(e) {
    <?php
    if ($this->getImageFloat()=='left') {
        $mojoY = $this->getZoomWidth() / 4;
        echo 'mojoX = 50;';
        echo 'mojoY = '.$mojoY.';';
    } else {
        $mojoX = ($this->getZoomWidth()+$this->getZoomCaptionPadding())+($this->getZoomImagePadding()+$this->getZoomBorderSize()) + 50;
        $mojoY = $this->getZoomWidth() / 4;
        echo 'mojoX = -'.$mojoX.';';
        echo 'mojoY = '.$mojoY.';';
    }
    ?>
    this.mojoTitle = this.title;
    var mojoCaption = (this.mojoTitle != "") ? this.mojoTitle : "";
    jQuery("body").append("<div id='mojoRadioZoom'><div><img src='" + this.href + "' alt='" + mojoCaption + "' /></div><?php if ($this->getZoomCaption() == 1) { ?><div style='font-size:<?php echo $this->getZoomCaptionSize(); ?>px; padding-top:<?php echo $this->getZoomCaptionPadding(); ?>px; max-width:<?php echo ($this->getZoomWidth()+$this->getZoomCaptionPadding()) + ($this->getZoomImagePadding() + $this->getZoomBorderSize()); ?>px;'>" + mojoCaption + "</div><?php } ?></div>");
        jQuery("#mojoRadioZoom")
            .css("top",(e.pageY - mojoY) + "px")
            .css("left",(e.pageX + mojoX) + "px")
            .fadeIn("slow");
        }, function() {
            this.title = this.mojoTitle;
            jQuery("#mojoRadioZoom").remove();
});
jQuery("a.mojoRadioZoom").mousemove(function(e) {
    jQuery("#mojoRadioZoom")
        .css("top", (e.pageY - mojoY) + "px")
        .css("left", (e.pageX + mojoX) + "px");
});
<?php endif; // $this->getImageZoom() ?>
</script>