<?php
/**
 * Mojo Creative & Technical Solutions LLC
 *
 * @category   GetSomeMojo
 * @package    GetSomeMojo_Bundledmojo
 * @copyright  Copyright (c) 2011-2013 Mojo Creative & Technical Solutions LLC (http://GetSome.MojoMage.com)
 * @license    http://getsome.mojomage.com/license/
 * @author     Mojo Creative & Technical Solutions LLC <info@MojoMage.com>
 *
 * @var $this Mage_Bundle_Block_Catalog_Product_View_Type_Bundle_Option_Checkbox
 */
?>
<?php $_option     = $this->getOption() ?>
<?php $_selections = $_option->getSelections() ?>
<div id="title-<?php echo $_option->getId() ?>">
<dt>
    <label<?php if ($_option->getRequired()) echo ' class="required"' ?>><?php echo $this->htmlEscape($_option->getTitle()) ?><?php if ($_option->getRequired()) echo '<em>*</em>' ?></label>
</dt>
<dd<?php echo ($_option->decoratedIsLast ? ' class="last"' : ''); ?>>
    <div class="input-box">
        <!-- Show Bundled Products -->
        <?php foreach ($_selections as $_selection) { ?>
        <?php $_productName = str_replace('"', '&nbsp;', $_selection->getName()); ?>
            <?php $_product = Mage::getModel('catalog/product')->load($_selection->getSelectionId()); ?>
            <div<?php if ($this->getYeaH4yeaH() && $this->getYeaH4checkbox()) echo ' class="bundledmojo_wrapper-' . $_selection->getSelectionId() . '" id="bundledmojo_wrapper"'; ?>>
                <?php if ($this->getBaseImage() || $this->getWishlist() || $this->getCompare()) { ?>
                <!-- The Following DIV dictates the float position of the Image and Layout -->
                <div style="float:<?php if (!strpos($this->helper('catalog/image')->init($_selection, 'small_image'), 'placeholder')) { echo $this->getImageFloat(); } else { echo 'right'; } ?>;" class="bundledmojo_image_wrapper">
                    <!--  Thumbnail Image -->
                    <?php if ($this->getBaseImage() && !strpos($this->helper('catalog/image')->init($_selection, 'small_image'), 'placeholder')) { ?>
                    <div class="bundledmojo_image" style="padding-<?php echo ($this->getImageFloat() == 'right' ? 'left' : 'right'); ?>:10px; padding-top: 5px;">
                        <a href="<?php echo $this->helper('catalog/image')->init($_selection, 'small_image')->constrainOnly(TRUE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize($this->getZoomWidth()); ?>" class="mojoCheckboxZoom" title="<?php echo $_productName; ?>" onclick="return false">
                            <img src="<?php echo $this->helper('catalog/image')->init($_selection, 'small_image')->constrainOnly(TRUE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize($this->getThumbSize()); ?>" alt="<?php echo $_productName; ?>" class="resize-<?php echo $_selection->getSelectionId(); ?> resize" id="imageZoom_toggle-<?php echo $_selection->getSelectionId(); ?>" />
                        </a>
                    </div>
                    <!--  End Thumbnail Image -->
                    <?php } ?>
                    <!--  If Wishlist or Add to Compare is Enabled Display Link(s) -->
                    <?php if ($this->getWishlist() || $this->getCompare()) { ?> 
                    <div style="<?php echo $this->getImageFloat() . ": 0; text-align:" . $this->getImageFloat() . ";"; ?>" class="mojowishcompare_wrapper imageZoom_toggle-<?php echo $_selection->getSelectionId(); ?>">
                        <?php if ($this->helper('wishlist')->isAllow() && $this->getWishlist()) { ?> 
                        <a href="<?php echo $this->helper('wishlist')->getAddUrl($_selection); ?>" class="link-compare">
                            <?php echo $this->__('Add To Wishlist'); ?>
                        </a>
                        <?php } ?>
                        <?php if ($this->helper('wishlist')->isAllow() && $this->getWishlist() && $this->getCompare()) { ?>
                        <br />
                        <?php } ?>
                        <?php if ($this->getCompare()) { ?> 
                        <a href="<?php echo $this->helper('catalog/product_compare')->getAddUrl($_selection); ?>" class="link-compare">
                            <?php echo $this->__('Add to Compare'); ?>
                        </a>
                        <?php } ?>
                    </div>
                    <!--  END showWishlist || showCompare -->
                    <?php } ?>
                </div> <!--  End .bundledmojo_image_wrapper -->
                <?php } ?>
                <div<?php echo  ($this->getYeaH4yeaH() && $this->getYeaH4checkbox() ? ' id="bundledmojo_desc_wrapper"' : ''); ?> style="<?php echo ($this->getImageFloat() == 'left' ? $this->getImageFloat() . ": 175px;" : "margin-right: 145px"); ?>">
                    <!--  Begin Checkbox Button -->
                    <?php $_isSelected = $this->_isSelected($_selection); ?>
                    <?php list($_defaultQty, $_canChangeQty) = $this->_getSelectionDefaultValues($_selection); ?>
                    <?php if (count($_selections) == 1 && $_option->getRequired() && !$_isSelected): ?>
                        <?php $_defaultQty = 1; ?>
                    <?php endif; ?>
                    <?php if (count($_selections) == 1 && $_option->getRequired()): ?>
                        <input type="hidden" name="bundle_option_qty1[<?php echo $_option->getId() ?>]" value="<?php echo $_selections[0]->getSelectionQty()*1; ?>"/>
                        <input type="hidden" id="bundle-option-<?php echo $_option->getId(); ?>-<?php echo $_selection->getSelectionId(); ?>" name="bundle_option[<?php echo $_option->getId(); ?>]" value="<?php echo $_selection->getSelectionId(); ?>"/>
                    <?php else: ?>
                    <input onclick="bundle.changeSelection(this)" class="checkbox bundle-option-<?php echo $_option->getId(); ?> <?php echo $_option->getRequired() ? 'validate-one-required-by-name' : ''; ?>" id="bundle-option-<?php echo $_option->getId(); ?>-<?php echo $_selection->getSelectionId(); ?>" type="checkbox" name="bundle_option[<?php echo $_option->getId(); ?>][]"<?php if ($_isSelected) echo ' checked="checked"' ?><?php if (!$_selection->isSaleable()) echo ' disabled="disabled"' ?> value="<?php echo $_selection->getSelectionId() ?>" />
                    <?php endif; ?>
                    <input type="hidden" name="bundle_option_qty1[<?php echo $_option->getId() ?>][<?php echo $_selection->getSelectionId() ?>]" value="<?php echo $_selection->getSelectionQty()*1; ?>"/>
                    <span class="label">
                        <label for="bundle-option-<?php echo $_option->getId(); ?>-<?php echo $_selection->getSelectionId(); ?>">
                            <?php if ($this->getProdNameUrl()): ?>
                            <a href="<?php echo $this->htmlEscape($_selection->getProductUrl()); ?>" title="<?php echo $this->getName($_selection); ?>" target="_blank">
                                <?php if ($this->getProdPrice()): ?>
                                    <?php echo $this->getSelectionTitlePrice($_selection, false); ?>
                                <?php else: ?>
                                    <?php echo $_productName; ?>
                                <?php endif; ?>
                            </a>
                            <?php else: ?>
                                <?php if ($this->getProdPrice()): ?>
                                    <?php echo $this->getSelectionTitlePrice($_selection, false); ?>
                                <?php else: ?>
                                    <?php echo $_productName; ?>
                                <?php endif; ?>
                            <?php endif; ?>
                        </label>
                        <?php if ($_canChangeQty && Mage::helper('bundledmojo')->getSystemConfigValue(GetSomeMojo_Bundledmojo_Block_Catalog_Product_View_Type_Bundle_Option_Checkbox::PROD_TYPE, GetSomeMojo_Bundledmojo_Helper_Data::XML_ENABLEQTY, Mage::app()->getStore())): ?>
                        <span class="qty-holder">
                            <label for="bundle-option-<?php echo $_option->getId() ?>-<?php echo $_selection->getSelectionId() ?>-qty-input">
                                <?php echo $this->__('Qty:') ?>&nbsp;
                            </label>
                            <input onkeyup="bundle.changeOptionQty(this, event)" onblur="bundle.changeOptionQty(this, event)" class="input-text qty<?php if (!$this->_showSingle() && !$_isSelected) echo ' qty-disabled' ?>" id="bundle-option-<?php echo $_option->getId() ?>-<?php echo $_selection->getSelectionId() ?>-qty-input" type="text" name="bundle_option_qty[<?php echo $_option->getId() ?>][<?php echo $_selection->getSelectionId() ?>]"<?php if (!$this->_showSingle() && !$_isSelected) echo ' disabled="disabled"' ?> value="<?php echo $_defaultQty ?>" />
                        </span>
                        <?php endif; ?>
                    </span>
                    <!--  End Checkbox Button -->
                    <!--  Check if Bundled Mojo is Enabled and if it is Begin Product Description -->
                    <?php if ($this->getYeaH4yeaH() && $this->getYeaH4checkbox()) { ?>
                    <br />
                    <!--  Begin Product Description -->
                    <div>
                        <!--  Text To Display -->
                        <?php if ($this->getShortDescInit() == 0 && $this->getShortDesc()) { ?>
                        <div id="<?php echo $_selection->getSelectionId(); ?>">
                            <a id="<?php echo $_selection->getSelectionId(); ?>" class="prodDescToggle">
                                <?php if ($this->getShortDescText()) echo $this->getShortDescText(); else echo $this->getShortDescTextDefault(); ?>
                            </a>
                        </div>
                        <?php } ?>
                        <?php if ($this->getShortDesc()) { ?>
                        <div class="<?php echo $_selection->getSelectionId(); ?> std" id="bundleDescUl"<?php if ($this->getShortDesc() && $this->getShortDescInit() == 0) echo ' style="display: none;"'; ?>>
                            <!--  Product Description -->
                            <?php $_productDesc = Mage::getSingleton('catalog/product')->load($_selection->getId()); ?>
                            <?php echo $_productDesc->getShortDescription(); ?>
                        </div>
                        <?php } ?>
                    </div>
                    <?php } ?>
                    <!--  End Product Description -->
                    <?php if ($_option->getRequired()) { ?>
                        <?php echo $this->setValidationContainer('bundle-option-' . $_option->getId() . '-' . $_selection->getSelectionId(), 'bundle-option-' . $_option->getId() . '-container'); ?>
                    <?php } ?>
                </div> <!--  End #bundledmojo_desc_wrapper -->
            </div> <!--  End #bundledmojo_wrapper --> 
            <?php if ($this->getBaseImage() && !strpos($this->helper('catalog/image')->init($_selection, 'small_image'), 'placeholder')): ?>
            <!-- Added for Bundled Mojo Layout -->
            <div style="clear: both;"></div>
            <?php endif; ?>
            <!--  End Show Bundled Products -->
        <!--  End $_selections as $_selection -->
        <?php } ?>
<div id="bundle-option-<?php echo $_option->getId(); ?>-container"></div>
</div> <!--  .input-box -->
</dd>
</div> <!--  #title-ID -->
<style type="text/css">
#mojoCheckboxZoom {
    position: absolute;
    border: <?php echo $this->getZoomBorderSize(); ?>px solid #<?php echo $this->getZoomBorderColor(); ?>;
    background: #<?php echo $this->getZoomBgColor(); ?>;
    padding: <?php echo $this->getZoomImagePadding(); ?>px;
    display: none;
    color: #<?php echo $this->getZoomFontColor(); ?>;
    z-index: 420;
}
</style>
<script type="text/javascript">
<?php if ($this->getShortDescInit() == 0) { ?>
    <?php foreach ($_selections as $_selection) { ?>
jQuery("#<?php echo $_selection->getSelectionId(); ?>").click(function () {
    jQuery(".<?php echo $_selection->getSelectionId(); ?>").slideToggle('slow', 'linear');
});
    <?php } ?>
<?php } ?>
<?php if ($this->getImageZoom()) { ?>
jQuery("a.mojoCheckboxZoom").hover(function(e) {
    <?php
    if ($this->getImageFloat() == 'left') {
        $mojoY = $this->getZoomWidth() / 4;
        echo 'mojoX = 50;';
        echo 'mojoY = ' . $mojoY . ';';
    } else {
        $mojoX = ($this->getZoomWidth() + $this->getZoomCaptionPadding()) + ($this->getZoomImagePadding() + $this->getZoomBorderSize()) + 50;
        $mojoY = $this->getZoomWidth() / 4;
        echo 'mojoX = -' . $mojoX . ';';
        echo 'mojoY = ' . $mojoY . ';';
    }
    ?>
    this.mojoTitle = this.title;
    var mojoCaption = (this.mojoTitle != "") ? this.mojoTitle : "";
    jQuery("body").append("<div id='mojoCheckboxZoom'><img src='" + this.href + "' alt='" + mojoCaption + "' /><?php if ($this->getZoomCaption() == 1) { ?><div style='font-size:<?php echo $this->getZoomCaptionSize(); ?>px; margin:<?php echo $this->getZoomCaptionPadding(); ?>px; max-width:<?php echo ($this->getZoomWidth() + $this->getZoomCaptionPadding()) + ($this->getZoomImagePadding() + $this->getZoomBorderSize()); ?>px;'>" + mojoCaption + "</div><?php } ?></div>");
    jQuery("#mojoCheckboxZoom")
        .css("top",(e.pageY - mojoY) + "px")
        .css("left",(e.pageX + mojoX) + "px")
        .fadeIn("slow");
    }, function() {
        this.title = this.mojoTitle;
        jQuery("#mojoCheckboxZoom").remove();
}); 
jQuery("a.mojoCheckboxZoom").mousemove(function(e) {
    jQuery("#mojoCheckboxZoom")
        .css("top",(e.pageY - mojoY) + "px")
        .css("left",(e.pageX + mojoX) + "px");
});
<?php } ?>
</script>