<div class="content-header">
    <table cellspacing="0" class="grid-header">
        <tr>
            <td><h3><?php echo $this->__('Send Return queue Report')?></h3></td>
        </tr>
    </table>
</div>
<?php if(count(Mage::app()->getWebsites())): ?>
    <?php echo $this->getChildHtml('store_switcher') ?>
<?php endif; ?>
<div class="entry-edit" style="margin-bottom:20px;">
    <form id="edit_form" name="edit_form">
        <input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
        <div style="">
            <table cellspacing="0" class="form-list-s">
                <tr>

                    <td class="label"><?php echo $this->__('Send date')?></td>
                    <td>
                        <?php
                        $startDate = '';
                        if(urldecode($this->getRequest()->getParam('startDate'))){
                            $startDate = date('m/d/Y', strtotime(urldecode($this->getRequest()->getParam('startDate'))));
                        }
                        echo $this->getLayout()->createBlock('core/html_date')
                            //->setTime('true')
                            ->setImage(Mage::getDesign()->getSkinUrl('images/grid-cal.gif'))
                            ->setFormat(Mage::app()->getLocale()->getDateFormat(Mage_Core_Model_Locale::FORMAT_TYPE_SHORT))
                            ->setName('startDate')
                            ->setValue($startDate)
                            ->setId('startDate')
                            ->setClass('datetime-picker input-text startDate')
                            ->toHtml();

                        ?>
                    </td>

                </tr>
                <tr>
                    <td colspan="4" class="a-right" style="padding-top: 10px;">
                        <button class="searchSend" type="button" style="display: inline-block;"><span>Search To Be Sent Items</span></button>
                        <button class="searchReturn" type="button" style="display: inline-block;"><span>Search To be Returned Items</span></button>
                    </td>
                </tr>
            </table>
        </div>
        <div class="" style="margin-top:20px;">
            <a class="refSerial" style="cursor:pointer;font-weight: bold;font-size:14px;">Return By Serial</a>
            <div id="returnBySerial" style="display: none;">
                <table>
                    <tr>
                        <td colspan="2">
                            Serial Number: <input type="text" class="returnInput" name="returnInput"/>
                        </td>
                        <td colspan="2">
                            <button class="returnSerial" type="button" style="display: inline-block;"><span>Return</span></button>
                        </td>
                    </tr>
                </table>
            </div>
        </div>
    </form>
</div>

<div id="sendTable" class="grid">

</div>
<div id="returnTable" class="grid">

</div>



<?php

?>

<script type="text/javascript">
    $jppr(document).ready(function() {

        $jppr('.refSerial').click(function(){
            if($jppr('#returnBySerial').is(':visible')){
                $jppr('#returnBySerial').hide();
            }else{
                $jppr('#returnBySerial').show();
            }
            return false;
        });

        $jppr('.searchSend').click(function(){
            Element.show('loading-mask');
            Element.hide('returnTable');
            var forStore = false;
            if($jppr('#store_switcher')) {
                forStore = $jppr('#store_switcher').val();
            }
            $jppr.ajax({
                cache: false,
                dataType: 'json',
                type: 'post',
                data: {
                    forStore: forStore
                },
                url: '<?php echo Mage::getUrl("payperrentals_admin/adminhtml_ajax/getSendQueueItems/",array('form_key'=> Mage::getSingleton('core/session')->getFormKey()))?>',
                success: function (data) {
                    Element.hide('loading-mask');
                    Element.show('sendTable');
                    $jppr('#sendTable').html(data.html);
                    var serviceUrl = '<?php echo Mage::getUrl("payperrentals_admin/adminhtml_ajax/getSerialNumbers/",array('form_key'=> Mage::getSingleton('core/session')->getFormKey()))?>';
                    getSerialNumbers('.sn', serviceUrl);

                    $jppr('.sendSelected').click(function(){
                        Element.show('loading-mask');
                        $jppr.ajax({
                            cache: false,
                            dataType: 'json',
                            type: 'post',
                            url: '<?php echo Mage::getUrl("payperrentals_admin/adminhtml_ajax/sendSelectedQueue/",array('form_key'=> Mage::getSingleton('core/session')->getFormKey()))?>',
                            data: $jppr('#sendTable *').serialize(),
                            success: function (data) {
                                Element.hide('loading-mask');
                                $jppr('.searchSend').trigger('click');
                            }
                        });

                        return false;
                    });

                }
            });
            return false;
        });

        $jppr('.searchReturn').click(function(){
            Element.show('loading-mask');
            Element.hide('sendTable');
            var forStore = false;
            if($jppr('#store_switcher')) {
                forStore = $jppr('#store_switcher').val();
            }
            $jppr.ajax({
                cache: false,
                dataType: 'json',
                type: 'post',
                url: '<?php echo Mage::getUrl("payperrentals_admin/adminhtml_ajax/getReturnQueueItems/",array('form_key'=> Mage::getSingleton('core/session')->getFormKey()))?>',
                data: {
                    'forStore':forStore,
                    'startDate':$jppr('.startDate').val()
                },
                success: function (data) {
                    Element.hide('loading-mask');
                    Element.show('returnTable');
                    $jppr('#returnTable').html(data.html);


                    $jppr('.returnSelected').click(function(){

                        Element.show('loading-mask');

                        $jppr.ajax({
                            cache: false,
                            dataType: 'json',
                            type: 'post',
                            url: '<?php echo Mage::getUrl("payperrentals_admin/adminhtml_ajax/returnSelected/",array('form_key'=> Mage::getSingleton('core/session')->getFormKey()))?>',
                            data: $jppr('#returnTable *').serialize(),
                            success: function (data) {
                                Element.hide('loading-mask');
                                $jppr('.returnRes').each(function(){
                                    if($jppr(this).is(':checked')){
                                        $jppr(this).parent().parent().remove();
                                    }
                                });
                            }
                        });

                        return false;
                    });

                }
            });
            return false;
        });


        $jppr('.returnSerial').click(function(){
            Element.show('loading-mask');
            Element.hide('sendTable');
            $jppr.ajax({
                cache: false,
                dataType: 'json',
                type: 'post',
                url: '<?php echo Mage::getUrl("payperrentals_admin/adminhtml_ajax/getReturnBySerialQueue/",array('form_key'=> Mage::getSingleton('core/session')->getFormKey()))?>',
                data: {
                    'sn':$jppr('.returnInput').val()
                },
                success: function (data) {
                    Element.hide('loading-mask');
                    Element.show('returnTable');
                    $jppr('#returnTable').html(data.html);


                    $jppr('.returnSelected').click(function(){

                        Element.show('loading-mask');

                        $jppr.ajax({
                            cache: false,
                            dataType: 'json',
                            type: 'post',
                            url: '<?php echo Mage::getUrl("payperrentals_admin/adminhtml_ajax/returnSelected/",array('form_key'=> Mage::getSingleton('core/session')->getFormKey()))?>',
                            data: $jppr('#returnTable *').serialize(),
                            success: function (data) {
                                Element.hide('loading-mask');
                                $jppr('.returnRes').each(function(){
                                    if($jppr(this).is(':checked')){
                                        $jppr(this).parent().parent().remove();
                                    }
                                });
                            }
                        });

                        return false;
                    });

                }
            });
            return false;
        });
        var serviceReturnUrl = '<?php echo Mage::getUrl("payperrentals_admin/adminhtml_ajax/getSentSerialNumbers/",array('form_key'=> Mage::getSingleton('core/session')->getFormKey()))?>';
        getSerialNumbers('.returnInput', serviceReturnUrl, {});
    });

</script>
<style type="text/css">


</style>