<?php
$threeMonths = new DateInterval('P12M');
$startDate = new DateTime();
$startDate->sub($threeMonths);
$endDate = new DateTime();
$endDate->add($threeMonths);
$collection = $this->getCollection($startDate->format('Y-m-d'), $endDate->format('Y-m-d'));
$events = $this->convertCollectionToEventsArray($collection);
$caltype = Mage::registry('caltype');
if($caltype == 'byorder'){
    $eventsJSON = $this->convertEventsArrayToJSON($events);
}
if($caltype == 'bystart'){
    $eventsCombinedStart = $this->combineStartandEndTurnoverArray($events,"start");
    $eventsCombinedEnd = $this->combineStartandEndTurnoverArray($events,"end");
    $eventsJSON = $this->convertEventsArrayToJSONstartend($eventsCombinedStart,"start");
    $eventsJSON .= $this->convertEventsArrayToJSONstartend($eventsCombinedEnd,"end");
    $eventsJSON = preg_replace('/,$/','',$eventsJSON);
}
//

?>
<script>

    $jppr(document).ready(function() {

        var date = new Date();
        var d = date.getDate();
        var m = date.getMonth();
        var y = date.getFullYear();

        var tooltip = $jppr('<div/>').qtip({
            id: 'fullcalendar',
            prerender: true,
            content: {
                text: ' ',
                title: {
                    button: true
                }
            },
            position: {
                my: 'bottom center',
                at: 'top center',
                target: 'mouse',
                viewport: $jppr(window),
                adjust: {
                    mouse: false,
                    scroll: false
                }
            },
            show: false,
            hide: false,
            style: 'qtip-light'
        }).qtip('api');

        $eventsJSON = [<?php echo $eventsJSON;?>];
        $jppr('#calendar').fullCalendar({
            eventClick: function(data, event, view) {
                var content = '<h3>'+data.title+'</h3>' +'<p>'+
                    data.description + '</p>';

                tooltip.set({
                    'content.text': content
                })
                    .reposition(event).show(event);
            },
            dayClick: function() { tooltip.hide() },
            eventResizeStart: function() { tooltip.hide() },
            eventDragStart: function() { tooltip.hide() },
            viewDisplay: function() { tooltip.hide() },
            defaultDate: new Date(y, m, d),
            editable: false,
            events: $eventsJSON

        });

        var cal = ics();
        $jppr.each($eventsJSON,function(i,$event){
            cal.addEvent($event.title, $event.description, '', $event.start, $event.end);
        });
    $jppr("#icaldownload").on('click',function(){
            cal.download('ical','.ics');
        });


    });

</script>
<button id="icaldownload" style="float:right;margin-bottom:10px;">Download iCal</button>
<div id='calendar'></div>
