<?php
	echo $this->getFormHtml();
?>
<script type="text/javascript">
$jppr(window).load(function(){
	$jppr.ajax({
		url: "<?php echo ITwebexperts_Payperrentals_Helper_Html::getDatepickerLocalePath();?>",
		dataType: "script",
		cache: true
	}).done(function() {
		$jppr.datepicker.regional['<?php echo ITwebexperts_Payperrentals_Helper_Html::getLocaleCodeForHtml();?>'];
	});
	$jppr.ajax({
		url: "<?php echo ITwebexperts_Payperrentals_Helper_Html::getDatetimepickerLocalePath();?>",
		dataType: "script",
		cache: true
	}).done(function() {
		$jppr.timepicker.regional['<?php echo ITwebexperts_Payperrentals_Helper_Html::getLocaleCodeForHtml();?>'];
	});

	$jppr("#date_from, #date_to").datetimepicker({
		showOn: "both",
		buttonImage: "<?php echo ITwebexperts_Payperrentals_Helper_Html::getCalendarPopupImage(); ?>",
		buttonImageOnly: true,
		buttonText: "Select date",
		timeFormat: 'HH:mm:ss',
		stepHour: 1,
		stepMinute: 1,
		showSecond: false,
		showButtonPanel: false,
		/* Keep JS Date Picker same format as MySQL */
		dateFormat: 'yy-mm-dd'
	});

	$jppr('#disabled_type').change(function(){
		if($jppr(this).val() == 'Daily'){
			$jppr('#repeat_days').show();
			$jppr("label[for='repeat_days']").show();
			valDateFrom = $jppr("#date_from").val();
			valDateTo = $jppr("#date_to").val();
			$jppr("#date_from, #date_to").datetimepicker("option","timeOnly", true);
			$jppr("#date_from").val(valDateFrom);
			$jppr("#date_to").val(valDateTo);
		}else{
			$jppr('#repeat_days').hide();
			$jppr("label[for='repeat_days']").hide();
			$jppr("#date_from, #date_to").datetimepicker("option","timeOnly", false);
		}
	});
	$jppr('#disabled_type').trigger('change');
});

	</script>