<?php /** $this ITwebexperts_Payperrentals_Block_Adminhtml_Serialreport */ ?>
<div class="content-header">
	<table cellspacing="0" class="grid-header">
		<tr>
			<td><h3><?php echo $this->__('Serial Report')?></h3></td>
		</tr>
	</table>
</div>
<?php if(count(Mage::app()->getWebsites())): ?>
    <?php echo $this->getChildHtml('store_switcher') ?>
<?php endif; ?>
<div class="entry-edit" style="margin-bottom:20px;">
	<form id="edit_form" name="edit_form">
		<input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
			<table cellspacing="5" class="form-list-s">
				<tr>
					<td class="label"><?php echo $this->__('Search by serial')?>: </td>
					<td class="input-ele"><input class="input-text serialName" id="serialName" name="serialName" value="<?php echo $this->getRequest()->getParam('serialName')?>"/></td>
					<td class="label"><?php echo $this->__('Search by product')?>: </td>
					<td><input type="text" class="productName" id="productName" name="productName" value="<?php echo $this->getRequest()->getParam('productName')?>"></td>
				</tr>
				<tr>
					<td colspan="4" class="a-right" style="padding-top: 10px;">
						<button class="searchBut" type="button" style="display: inline-block;" onclick="form.submit()"><span><?php echo $this->__('Search')?></span></button>
                        <button class="searchAllBut" type="button" style="display: inline-block;"><span><?php echo $this->__('Reset')?></span></button>
					</td>
				</tr>
			</table>
	</form>

</div>

<div id="calendarProducts"></div>

<div id="pager">
	<?php
	echo $this->getPagerHtml();
	?>
</div>

<?php list($monthFormat, $weekFormat, $dayFormat) = $this->getDatesFormat();?>
<?php list($monthFormatC, $weekFormatC, $dayFormatC) = $this->getDatesFormatCalendar();?>

<?php

	$productsCollection = $this->getPager()->getCollection();
	$resources = array();
    $serialNumbers = array();
	foreach($productsCollection as $resProduct) {
		$Product = Mage::getModel('catalog/product')->load($resProduct->getId());
		$coll = $this->getSerialCollection($resProduct->getId());
        $resources = $this->getResource($Product,$coll,$resources);
	}
	$resources_JSON_array = json_encode($resources);
?>

<script type="text/javascript">

	$jppr(document).ready(function() {

		var date = new Date();
		var d = date.getDate();
		var m = date.getMonth();
		var y = date.getFullYear();

		var calendar = $jppr('#calendarProducts').fullCalendar({
			header: {
				left: 'prev,next today',
				center: 'title',
				right: 'resourceDay,resourceWeek,resourceMonth'
			},
            titleFormat: {
                resourceMonth: '<?php echo $monthFormat;?>',
                resourceWeek: '<?php echo $weekFormat;?>',
                resourceDay: '<?php echo $dayFormat;?>'
            },
            columnFormat:{
                resourceMonth: '<?php echo $monthFormatC;?>',
                resourceWeek: '<?php echo $weekFormatC;?>'
            },
            defaultView: 'resourceMonth',
			firstDay: 1,
			editable: false,
			selectable: false,
			minTime: <?php echo intval(Mage::getStoreConfig(ITwebexperts_Payperrentals_Helper_Config::XML_PATH_STORE_OPEN_TIME));?>,
			maxTime: <?php echo (intval(Mage::getStoreConfig(ITwebexperts_Payperrentals_Helper_Config::XML_PATH_STORE_CLOSE_TIME))+1);?>,
			slotMinutes: <?php echo Mage::helper('payperrentals/config')->getTimeIncrement();?>,
			selectHelper: false,
			resources: <?php echo $resources_JSON_array;?>,
			events:{
				url: '<?php echo Mage::getUrl("payperrentals_admin/adminhtml_ajax/getSerialevents/",array('form_key'=> Mage::getSingleton('core/session')->getFormKey()))?>',
				type: 'POST',
				data: {
					productsids: '<?php echo implode(',',$serialNumbers);?>'
				},
				error: function() {
					alert('there was an error while fetching events!');
				},
				color: 'yellow',   // a non-ajax option
				textColor: 'black' // a non-ajax option
			},
            //height: calcCalendarHeight(),
            aspectRatio: 12,
			loading: function (bool) {
				if (bool)
					$jppr('#loading-mask').show();
				else{
					$jppr('#loading-mask').hide();
                    $jppr('a.fc-event').each(function(){
                        $jppr(this).qtip({
                            content: {
                                text: $jppr(this).attr('href'),
                                title: {
                                    text: 'Order Details',
                                    button: 'Close' // Close button
                                }
                            },
                            position: {
                                at: 'top left',
                                adjust: {
                                    y: -140,
                                    x: -100
                                }
                            },
                            style: { classes: 'qtip-shadow qtip-red' }
                        });
                    });
				}
			},
            viewDisplay: function(view) {
                $jppr('a.fc-event').each(function(){
                    $jppr(this).qtip({
                        content: {
                            text: $jppr(this).attr('href'),
                            title: {
                                text: 'Order Details',
                                button: 'Close' // Close button
                            }
                        },
                        position: {
                            at: 'top left',
                            adjust: {
                                y: -140,
                                x: -100
                            }
                        },
                        style: { classes: 'qtip-shadow qtip-red' }
                    });
                });
            },
            eventClick: function(event) {
                if (event.url) {
					window.open(event.textColor);
                    return false;
                }
            }

		});

		function calcCalendarHeight() {
            return $jppr(window).height() - 40;
		}

		$jppr(window).resize(function() {
			$jppr('#calendarProducts').fullCalendar('option', 'height', calcCalendarHeight());
		});
	});

</script>
<style type="text/css">
	#pager ol li{
		display: inline-block;
	}
	#pager .limiter{
		display: block;
	}
	#pager .pages{
		display: block;
		margin-top:20px;
		font-size:14px;
	}
	#pager ol{
		display: inline-block;
	}
	.notreturnedColor span, .returnedColor span{
		color:#ffffff !important;
	}

</style>