<div class="content-header">
	<table cellspacing="0" class="grid-header">
		<tr>
			<td><h3><?php echo $this->__('Send Return Report')?></h3></td>
		</tr>
	</table>
</div>
<?php if(count(Mage::app()->getWebsites())): ?>
    <?php echo $this->getChildHtml('store_switcher') ?>
<?php endif; ?>
<div class="entry-edit" style="margin-bottom:20px;">
	<form id="edit_form" name="edit_form">
		<input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
		<div style="">
			<table cellspacing="5" class="form-list-s">
				<tr>

					<td class="label"> &nbsp;&nbsp;<?php echo $this->__('Start date From:')?> &nbsp;</td>
					<td>
						<?php
						$startdatefrom = '';
						if(urldecode($this->getRequest()->getParam('startDatefrom'))){
							$startdatefrom = date('m/d/Y', strtotime(urldecode($this->getRequest()->getParam('startDatefrom'))));
						}
						echo $this->getCalendar($startdatefrom, 'startDatefrom');
						?>
					</td>

                    <td class="label"> &nbsp;&nbsp;<?php echo $this->__('Start date To:')?> &nbsp;</td>
                    <td>
                        <?php
                        $startdateto = '';
                        if(urldecode($this->getRequest()->getParam('startDateto'))){
                            $startdateto = date('m/d/Y', strtotime(urldecode($this->getRequest()->getParam('startDateto'))));
                        }
                        echo $this->getCalendar($startdateto,'startDateto');
                        ?>
                    </td>
                    </tr>
                <tr>

					<td class="label"> &nbsp;&nbsp;<?php echo $this->__('End Date From:') ?> &nbsp;</td>
					<td>
						<?php
						$enddatefrom = '';
						if(urldecode($this->getRequest()->getParam('endDatefrom'))){
							$enddatefrom = date('m/d/Y', strtotime(urldecode($this->getRequest()->getParam('endDatefrom'))));
						}
						echo $this->getCalendar($enddatefrom,'endDatefrom');
						?>
					</td>

                    <td class="label"> &nbsp;&nbsp;<?php echo $this->__('End Date To:') ?> &nbsp;</td>
                    <td>
                        <?php
                        $enddateto = '';
                        if(urldecode($this->getRequest()->getParam('endDateto'))){
                            $enddateto = date('m/d/Y', strtotime(urldecode($this->getRequest()->getParam('endDateto'))));
                        }
                        echo $this->getCalendar($enddateto,'endDateto');
                        ?>
                    </td>

				</tr>
				<tr>
					<td colspan="4" class="a-right" style="padding-top: 10px;">
						<button class="searchSend" type="button" style="display: inline-block;"><span>Search To Be Sent Items</span></button>
						<button class="searchReturn" type="button" style="display: inline-block;"><span>Search To be Returned Items</span></button>
					</td>
				</tr>
			</table>
			</div>
			<div class="" style="margin-top:20px;">
				<a class="refSerial" style="cursor:pointer;font-weight: bold;font-size:14px;">Return By Serial</a>
				<div id="returnBySerial" style="display: none;">
					<table>
						<tr>
							<td colspan="2">
								Serial Number: <input type="text" class="returnInput" name="returnInput"/>
							</td>
							<td colspan="2">
								<button class="returnSerial" type="button" style="display: inline-block;"><span>Return</span></button>
							</td>
						</tr>
					</table>
				</div>
			</div>
	</form>
</div>

<div id="sendTable" class="grid">

</div>
<div id="returnTable" class="grid">

</div>



<?php

?>

<script type="text/javascript">
	$jppr(document).ready(function() {

		$jppr('.refSerial').click(function(){
			if($jppr('#returnBySerial').is(':visible')){
				$jppr('#returnBySerial').hide();
			}else{
				$jppr('#returnBySerial').show();
			}
			return false;
		});

		$jppr('.searchSend').click(function(){
			Element.show('loading-mask');
			Element.hide('returnTable');
            var forStore = false;
            if($jppr('#store_switcher')) {
                forStore = $jppr('#store_switcher').val();
            }
            $jppr.ajax({
                cache: false,
                dataType: 'json',
                type: 'post',
                url: '<?php echo Mage::getUrl("payperrentals_admin/adminhtml_ajax/getSendItems/",array('form_key'=> Mage::getSingleton('core/session')->getFormKey()))?>',
                data: {
                    'startDatefrom':$jppr('.startDatefrom').val(),
                    'startDateto':$jppr('.startDateto').val(),
                    'endDatefrom':$jppr('.endDatefrom').val(),
                    'endDateto':$jppr('.endDateto').val(),
                    forStore: forStore
                },
				success: function (data) {
					Element.hide('loading-mask');
					Element.show('sendTable');
					$jppr('#sendTable').html(data.html);
                    var serviceUrl = '<?php echo Mage::getUrl("payperrentals_admin/adminhtml_ajax/getSerialNumbers/",array('form_key'=> Mage::getSingleton('core/session')->getFormKey()))?>';
                    getSerialNumbers('.sn',serviceUrl);

                    $jppr('.sendSelected').click(function(){

						Element.show('loading-mask');
                        $('messages').update();

						$jppr.ajax({
							cache: false,
							dataType: 'json',
							type: 'post',
							url: '<?php echo Mage::getUrl("payperrentals_admin/adminhtml_ajax/sendSelected/",array('form_key'=> Mage::getSingleton('core/session')->getFormKey()))?>',
							data: $jppr('#sendTable *').serialize(),
							success: function (data) {
								Element.hide('loading-mask');
								$jppr('.sendRes').each(function(){
									if($jppr(this).is(':checked')){
										$jppr(this).parent().parent().remove();
									}
								});
                                if(data.error) {
                                    $('messages').update('<ul class="messages"><li class="error-msg"><ul><li><span>' + data.error + '</span></li></ul></li></ul>');
                                }
							}
						});

						return false;
					});

				}
			});
			return false;
		});

		$jppr('.searchReturn').click(function(){
			Element.show('loading-mask');
			Element.hide('sendTable');
            var forStore = false;
            if($jppr('#store_switcher')) {
                forStore = $jppr('#store_switcher').val();
            }
            $jppr.ajax({
                cache: false,
                dataType: 'json',
                type: 'post',
                url: '<?php echo Mage::getUrl("payperrentals_admin/adminhtml_ajax/getReturnItems/",array('form_key'=> Mage::getSingleton('core/session')->getFormKey()))?>',
                data: {
                    'startDatefrom':$jppr('.startDatefrom').val(),
                    'startDateto':$jppr('.startDateto').val(),
                    'endDatefrom':$jppr('.endDatefrom').val(),
                    'endDateto':$jppr('.endDateto').val(),
                    forStore: forStore
                },
				success: function (data) {
					Element.hide('loading-mask');
					Element.show('returnTable');
					$jppr('#returnTable').html(data.html);


					$jppr('.returnSelected').click(function(){

						Element.show('loading-mask');

						$jppr.ajax({
							cache: false,
							dataType: 'json',
							type: 'post',
							url: '<?php echo Mage::getUrl("payperrentals_admin/adminhtml_ajax/returnSelected/",array('form_key'=> Mage::getSingleton('core/session')->getFormKey()))?>',
							data: $jppr('#returnTable *').serialize(),
							success: function (data) {
								Element.hide('loading-mask');
								$jppr('.returnRes').each(function(){
									if($jppr(this).is(':checked')){
										$jppr(this).parent().parent().remove();
									}
								});
							}
						});

						return false;
					});

				}
			});
			return false;
		});


		$jppr('.returnSerial').click(function(){
			Element.show('loading-mask');
			Element.hide('sendTable');
			$jppr.ajax({
				cache: false,
				dataType: 'json',
				type: 'post',
				url: '<?php echo Mage::getUrl("payperrentals_admin/adminhtml_ajax/getReturnBySerial/",array('form_key'=> Mage::getSingleton('core/session')->getFormKey()))?>',
				data: {
					'sn':$jppr('.returnInput').val()
				},
				success: function (data) {
					Element.hide('loading-mask');
					Element.show('returnTable');
					$jppr('#returnTable').html(data.html);


					$jppr('.returnSelected').click(function(){

						Element.show('loading-mask');

						$jppr.ajax({
							cache: false,
							dataType: 'json',
							type: 'post',
							url: '<?php echo Mage::getUrl("payperrentals_admin/adminhtml_ajax/returnSelected/",array('form_key'=> Mage::getSingleton('core/session')->getFormKey()))?>',
							data: $jppr('#returnTable *').serialize(),
							success: function (data) {
								Element.hide('loading-mask');
								$jppr('.returnRes').each(function(){
									if($jppr(this).is(':checked')){
										$jppr(this).parent().parent().remove();
									}
								});
							}
						});

						return false;
					});

				}
			});
			return false;
		});

        var serviceReturnUrl = '<?php echo Mage::getUrl("payperrentals_admin/adminhtml_ajax/getSentSerialNumbers/",array('form_key'=> Mage::getSingleton('core/session')->getFormKey()))?>';
        getSerialNumbers('.returnInput', serviceReturnUrl, {});


		$jppr('.searchAllBut').click(function(){
			var location = '<?php echo  Mage::getUrl("payperrentals_admin/adminhtml_quantityreport/index",array('key'=> $this->getRequest()->getParam('key')))?>';
			if($jppr('.gotoDate').val() != ''){
				location = location +'gotoDate/'+$jppr.formatDateTime('yy-mm-dd',new Date($jppr('.gotoDate').val()));
			}
			window.location.href = location;
		});
		<?php
	    if(urldecode($this->getRequest()->getParam('sending'))){
		?>
		$jppr('.searchSend').trigger('click');
		<?php
		}
		?>
	<?php
	if(urldecode($this->getRequest()->getParam('returning'))){
		?>
        $jppr('.searchReturn').trigger('click');
		<?php
	}
	?>
	});

</script>
<style type="text/css">


</style>