<?php
$sigimage = Mage::getBaseUrl('media') . 'pdfs/signatures/' . $this->getOrder()->getSignatureImage();
?>
<style type="text/css">
    #signatureparent {
        color:darkblue;
        background-color:darkgrey;
        max-width:600px;
        padding:20px;
    }

    /*This is the div within which the signature canvas is fitted*/
    #signature {
        border: 2px dotted black;
        background-color:lightgrey;
    }

    /* Drawing the 'gripper' for touch-enabled devices */
    html.touch #content {
        float:left;
        width:92%;
    }
    html.touch #scrollgrabber {
        float:right;
        width:4%;
        margin-right:2%;
        background-image:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAAFCAAAAACh79lDAAAAAXNSR0IArs4c6QAAABJJREFUCB1jmMmQxjCT4T/DfwAPLgOXlrt3IwAAAABJRU5ErkJggg==)
    }
    html.borderradius #scrollgrabber {
        border-radius: 1em;
    }

</style>
<?php if($this->getOrder()->getSignatureImage()): ?>
    <?php echo $this->__('The signature captured can be seen below. If you need to modify it you can do so with the form.') ?><br /><br />
    <img src="<?php echo $sigimage . '?' . filemtime(Mage::getBaseDir('media') . DS .  'pdfs' . DS . 'signatures' . DS . $this->getOrder()->getSignatureImage()); ?>"><br /><br />
<?php endif ?>
<form action="<?php echo $this->getFormaction()?>" method="POST">
    <?php echo $this->__('By signing below you are agreeing to the terms of the Rental Contract for Order #')?> <?php echo $this->getOrderid()?>.<br /><br />
    <div>
        <div id="content">
            <div id="signatureparent">
                <div id="signature"></div></div>
            <div id="tools"></div>
        </div>
        <div id="scrollgrabber"></div><br />
    </div>
    <input type="hidden" name="signaturecode" id="signaturecode">
    <input type="hidden" name="signatureimage" id="signatureimage">
    <input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>" />
    <input type="hidden" name="order_id" value="<?php echo $this->getOrderid()?>">
    <label for="typedsignature">Type Signature: </label>
    <input type="text" name="typedsignature" id="typedsignature"><br /><br />
    Signed on: <?php echo Mage::helper('core')->formatDate(NULL, 'medium', false); ?><br /><br />
    <button><span><span><span>Sign Contract</span></span></span></button>
</form>
<script>
    /*  @preserve
     jQuery pub/sub plugin by Peter Higgins (dante@dojotoolkit.org)
     Loosely based on Dojo publish/subscribe API, limited in scope. Rewritten blindly.
     Original is (c) Dojo Foundation 2004-2010. Released under either AFL or new BSD, see:
     http://dojofoundation.org/license for more information.
     */
    var topics = {};
    $jppr.publish = function(topic, args) {
        if (topics[topic]) {
            var currentTopic = topics[topic],
                args = args || {};

            for (var i = 0, j = currentTopic.length; i < j; i++) {
                currentTopic[i].call($, args);
            }
        }
    };
    $jppr.subscribe = function(topic, callback) {
        if (!topics[topic]) {
            topics[topic] = [];
        }
        topics[topic].push(callback);
        return {
            "topic": topic,
            "callback": callback
        };
    };
    $jppr.unsubscribe = function(handle) {
        var topic = handle.topic;
        if (topics[topic]) {
            var currentTopic = topics[topic];

            for (var i = 0, j = currentTopic.length; i < j; i++) {
                if (currentTopic[i] === handle.callback) {
                    currentTopic.splice(i, 1);
                }
            }
        }
    };

</script>
<script>
    $jppr(document).ready(function() {
        // This is the part where jSignature is initialized.
        var $sigdiv = $jppr("#signature").jSignature({'UndoButton':true})
        if (Modernizr.touch){
            $jppr('#scrollgrabber').height($jppr('#content').height())
        }
        $jppr('form').submit(function(event){
            var $signature = $jppr('#signature').jSignature('getData','base30');
            var $signaturetext = $jppr('#typedsignature').val();
            var $signatureimage = $jppr('#signature').jSignature('getData','svg');
            $jppr('#signatureimage').val($signatureimage);
            if($signature[1] == '') {
                alert('<?php echo $this->__('Signature field must be signed')?>');
                event.preventDefault();
            } else if($signaturetext == '') {
                alert('<?php echo $this->__('You must fill in the typed signature input field')?>');
                event.preventDefault();
            } else {
                $jppr('#signaturecode').val($signature);
                return;
            }

        });
    })
</script>