<script type="text/javascript"
        src="<?php echo $this->getSkinUrl('joomlart/jmproductsdeal/js/jquery.jcountdown1.3.js') ?>"></script>
<div class="jm-product-onedeal <?php echo $config['mode']; ?> clearfix block">
    <?php if ($config['title']) { ?>
        <div class="page-title category-title"><h1><?php echo $config['title']; ?></h1></div><?php }; ?>
    <?php $_products = $this->getProductCollection(); ?>

    <?php
    $width = 100;
    $thumbnailw = $config['width'];
    $thumbnailh = $config['height'];
    $numberchar = $config['max'];

    if ($config['perrow']) $width = 100 / $config['perrow'];
    $width = "style=\"width:{$width}%;\"";
    $return = false;
    ?>
    <?php if ($config['mode'] == 'list'): ?>
        <div class="category-products">
        </div>
    <?php else: ?>
        <div class="listing-type-grid category-products">
            <?php if (($_products = $this->getProductCollection()) && $_collectionSize = $_products->getSize()) { ?>
                <ul class="products-grid">
                    <?php $i = 0;
                    foreach ($_products->getItems() as $_product) {
                        $j = 0;
                        $_rowCount = ceil($_collectionSize / $config['perrow']);
                        if ($i % $config['perrow'] == 0) : $j++; endif;
                        $i++;
                        ?>
                        <li class="item <?php if ($j == $_rowCount) : echo "item-row-last"; endif; ?> <?php if (($i - 1) % $config['perrow'] == 0): ?> first<?php elseif ($i % $config['perrow'] == 0): ?> last<?php endif; ?>" <?php echo $width; ?>>
                            <div class="inner">
                                <a class="product-image" title="<?php echo $this->htmlEscape($_product->getName()) ?>"
                                   href="<?php echo $_product->getProductUrl() ?>">
                                    <img
                                        src="<?php echo $this->helper('catalog/image')->init($_product, 'thumbnail')->resize($thumbnailw, $thumbnailh)->setWatermarkSize('30x10'); ?>"
                                        alt="<?php echo $this->htmlEscape($_product->getName()) ?>"/>
                                </a>
                                <a class="product-name" title="<?php echo $this->htmlEscape($_product->getName()) ?>"
                                   href="<?php echo $_product->getProductUrl() ?>">
                                    <?php
                                    if (strlen($_product->getName()) > 30) :
                                        echo substr($_product->getName(), 0, 24) . '...';
                                    else :
                                        echo $_product->getName();
                                    endif;
                                    ?>
                                </a>

                                <?php echo $this->getReviewsSummaryHtml($_product, true, true) ?>
                                <?php if ($config['showitemsold'] || $config['showsaleenddate'] || $config['showdiscount'] || $config['showsaveamount'] || $config['showproductleft']): ?>
                                    <?php if ($config['showsaleenddate']): ?>
                                        <?php
                                        //Load special price end date for timer
                                        $specialPriceEndDate = date("Y-m-d 23:59:59", strtotime($_product->getSpecialToDate()));
                                        //Caluclate remaining time in seconds
                                        //time now
                                        //$now = Mage::getModel('core/date')->timestamp(time());
                                        $now = strtotime(Mage::app()->getLocale()->date()->toString(Varien_Date::DATETIME_INTERNAL_FORMAT));

                                        $end = strtotime($specialPriceEndDate);
                                        $time = $end - $now;
                                        if ($time < 0) { // is there any time left
                                            $time = 0;
                                            // echo "<strong>Ended time ". $time."</strong>";
                                        } else { // if there is time left
                                            //echo "now".$now." end".$end." time".$time;  //test for $time left to start javascript countdown
                                            ?>
                                            <?php $endDate = date("F d, Y H:i:s", strtotime($specialPriceEndDate)); ?>
                                            <script type="text/javascript">
                                                //<![CDATA[
                                                jQuery(document).ready(function () {
                                                    jQuery("#sale-ends<?php echo $_product->getId();  ?>").countdown({
                                                        date: "<?php echo strtolower($endDate); ?>", //Counting TO a date
                                                        cdate: "<?php echo strtolower(date("F d, Y H:i:s", $now)); ?>",
                                                        updateTime: 999,
                                                        htmlTemplate: "<span class='item-count item-count-days'>%{d} <span class=\"cd-time\">days</span></span> <span class='item-count'> %{h} <span class=\"cd-time\">hours</span></span> <span class='item-count'> %{m} <span class=\"cd-time\">mins</span></span> <span class='item-count'> %{s} <span class=\"cd-time\">sec</span></span>",
                                                        //date: "july 1, 2011 19:24", //Counting TO a date
                                                        onChange: function (event, timer) {
                                                        },
                                                        onComplete: function (event) {

                                                            $(this).html("Completed");
                                                        },
                                                        leadingZero: true,
                                                        direction: "down"
                                                    });
                                                });
                                                //]]>
                                            </script>
                                            <ul class="deals-info">
                                            <li class="time-left">
                                                <!--<strong>  Time left: </strong>-->
                                                <strong class="sale-ends"
                                                        id="sale-ends<?php echo $_product->getId(); ?>">Time
                                                    left:</strong>
                                            </li>
                                        <?php } ?>
                                    <?php endif; ?>

                                    <?php if ($config['showdiscount']): ?>
                                        <li class="discount">
                                            <strong> <?php echo $this->__('Discount') ?></strong> <br/>
                                            <?php if ($_product->getData('special_price')): ?>
                                                <?php
                                                $_formattedActualPrice = Mage::helper('core')->currency($_product->getPrice(), false, false);
                                                $specialPrice = $_product->getFinalPrice();
                                                $_formattedSpecialPrice = Mage::helper('core')->currency($_product->getFinalPrice(), false, false);
                                                $orignalPrice = $_product->getData('price');
                                                $discount = round((($orignalPrice - $specialPrice) / $orignalPrice) * 100);
                                                ?>
                                            <?php else: $discount = 0; endif; ?>
                                            <strong class="discount"><?php echo $discount . ' %'; ?> </strong>
                                        </li>
                                    <?php endif; ?>

                                    <?php if ($config['showsaveamount']): ?>
                                        <li class="save-moneys">
                                            <div class="save-money">
                                                <strong><?php echo $this->__('Save') ?></strong> <br/>
                                                <strong
                                                    class="save"><?php echo Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol() . '' . round($_formattedActualPrice - $_formattedSpecialPrice); ?></strong>
                                            </div>
                                        </li>
                                    <?php endif; ?>

                                    <?php if ($config['showproductleft']): ?>
                                        <li class="qt-remain">
                                            <?php $qtyStock = Mage::getModel('cataloginventory/stock_item')->loadByProduct($_product)->getQty(); ?>
                                            <div class="number-product-left">
                                                <strong><?php echo $this->__('Qty Remaining') . ': '; ?></strong>
                                                <br/> <?php echo round($qtyStock); ?></div>
                                        </li>
                                    <?php endif; ?>

                                    <?php if ($config['showitemsold']): ?>
                                        <li class="purchased">
                                            <?php
                                            $sku = nl2br($_product->getSku());
                                            $_productitem = Mage::getResourceModel('reports/product_collection')
                                                ->addOrderedQty()
                                                ->addAttributeToFilter('sku', $sku)
                                                ->setOrder('ordered_qty', 'desc')
                                                ->getFirstItem();
                                            echo '<div class="number-items-sold"><strong>' . $this->__('Purchased') . '</strong>: ';
                                            echo (int)$_productitem->ordered_qty . '</div>'; ?>
                                        </li>
                                    <?php endif; ?>
                                    </ul>
                                <?php endif; ?>
                                <a class="view-details" title="<?php echo $this->htmlEscape($_product->getName()) ?>"
                                   href="<?php echo Mage::getBaseUrl() . 'deals'; ?>">View detail deals</a>
                            </div>
                        </li>
                    <?php } ?>
                </ul>
                <script
                    type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd', 'even', 'first', 'last'])</script>
            <?php } ?>
        </div>
    <?php endif; ?>
</div>