<?php

?>
<?php

$_htmlId      = $this->getElement()->getHtmlId() ?>
<?php $_htmlClass   = $this->getElement()->getClass() ?>
<?php $_htmlName    = $this->getElement()->getName() ?>
<?php $_readonly    = $this->getElement()->getReadonly() ?>
<?php $_showWebsite = 0 && !Mage::app()->isSingleStoreMode() ?>
<?php $_priceValueValidation = $this->getPriceValidation('validate-greater-than-zero'); ?>


<tr>
    <td class="label"><?php echo $this->getElement()->getLabel() ?></td>
    <td colspan="11" class="grid excludedates">
        <table cellspacing="0" class="data border" id="excludedates_table">
            <?php if ($_showWebsite): ?>
                <col width="135" />
            <?php endif; ?>
            <col width="120" />
            <col width="95" />
            <col  />
            <col />
            <col width="1" />
            <thead>
            <tr class="headings">
                <th <?php if (!$_showWebsite): ?>style="display:none"<?php endif; ?>><?php echo Mage::helper('payperrentals')->__('Website') ?></th>
                <th><?php echo Mage::helper('payperrentals')->__('Disabled From') ?></th>
                <th><?php echo Mage::helper('payperrentals')->__('Disabled To') ?></th>
                <th><?php echo Mage::helper('payperrentals')->__('Repeat') ?></th>
                <th><?php echo Mage::helper('payperrentals')->__('Exclude From') ?></th>
                <th class="last"><?php echo Mage::helper('payperrentals')->__('Action') ?></th>
            </tr>
            </thead>
            <tbody id="<?php echo $_htmlId ?>_container"></tbody>
            <tfoot>
            <tr>
                <td <?php if (!$_showWebsite): ?>style="display:none"<?php endif; ?>></td>
                <td colspan="5" class="a-right"><?php echo $this->getChildHtml('add_button'); ?></td>
            </tr>
            </tfoot>
        </table>

        <script type="text/javascript">
            //<![CDATA[
            var excludedDatesRowTemplate = '<tr>'
                + '<td<?php if (!$_showWebsite): ?> style="display:none"<?php endif; ?>>'
                + '<select class="<?php echo $_htmlClass ?>" name="<?php echo $_htmlName ?>[{{index}}][website_id]" id="excludedates_row_{{index}}_website">'
                <?php foreach ($this->getWebsites() as $_websiteId => $_info): ?>
                + '<option value="<?php echo $_websiteId ?>"><?php echo $this->jsQuoteEscape($this->htmlEscape($_info['name'])) ?><?php if (!empty($_info['currency'])): ?> [<?php echo $this->htmlEscape($_info['currency']) ?>]<?php endif; ?></option>'
                <?php endforeach ?>
                + '</select></td>'
                + '<td class="nobr"><?php echo $this->makeDateTimeBlock($_htmlName, 'excludefrom') ?></td>'
                + '<td class="nobr"><?php echo $this->makeDateTimeBlock($_htmlName, 'excludeto') ?></td>'
                + '<td><select class="<?php echo $_htmlClass ?> repeatperiod" name="<?php echo $_htmlName ?>[{{index}}][repeatperiod]" id="excludedates_row_{{index}}_repeatperiod">'
                + '<option value="<?php echo 'none'; ?>"><?php echo Mage::helper('payperrentals')->__('None');?></option>'
                + '<option value="<?php echo 'dayweek'; ?>"><?php echo Mage::helper('payperrentals')->__('Day of Week');?></option>'
                + '<option value="<?php echo 'daily'; ?>"><?php echo Mage::helper('payperrentals')->__('Daily');?></option>'
                + '<option value="<?php echo 'monthly';?>"><?php echo Mage::helper('payperrentals')->__('Monthly');?></option>'
                + '<option value="<?php echo 'yearly'; ?>"><?php echo Mage::helper('payperrentals')->__('Yearly');?></option>'
                + '</select></td>'
                + '<td><select class="<?php echo $_htmlClass ?> excludedaysfrom" name="<?php echo $_htmlName ?>[{{index}}][excludedaysfrom]" id="excludedates_row_{{index}}_excludedaysfrom">'
                + '<option value="<?php echo ITwebexperts_Payperrentals_Model_Source_Excludedaysfrom::CALENDAR; ?>"><?php echo Mage::helper('payperrentals')->__('Calendar');?></option>'
                + '<option value="<?php echo ITwebexperts_Payperrentals_Model_Source_Excludedaysfrom::PRICE; ?>"><?php echo Mage::helper('payperrentals')->__('Price');?></option>'
                + '<option value="<?php echo ITwebexperts_Payperrentals_Model_Source_Excludedaysfrom::BOTH; ?>"><?php echo Mage::helper('payperrentals')->__('Both');?></option>'

                + '</select></td>'
                + '<td class="last"><input type="hidden" name="<?php echo $_htmlName ?>[{{index}}][delete]" class="delete" value="" id="excludedates_row_{{index}}_delete" />'
                + '<button title="<?php echo Mage::helper('catalog')->__("Delete Tier") ?>" type="button" class="scalable delete icon-btn delete-product-option" id="excludedates_row_{{index}}_delete_button" onclick="return excludedDatesControl.deleteItem(event);">'
                + '<span><span><span><?php echo Mage::helper('catalog')->__("Delete") ?></span></span></span></button></td>'
                + '</tr>';

            var excludedDatesControl = {
                template: new Template(excludedDatesRowTemplate, new RegExp('(^|.|\\r|\\n)({{\\s*(\\w+)\\s*}})', "")),
                itemsCount: 0,
                addItem : function () {
                    <?php if ($_readonly): ?>
                    if (arguments.length < 5) {
                        return;
                    }
                    <?php endif; ?>
                    var data = {
                        website_id: '<?php echo $this->getDefaultWebsite() ?>',
                        repeatperiod: '<?php echo 'none'; ?>',
                        excludefrom: '',
                        excludeto: '',
                        excludedaysfrom: '<?php echo ITwebexperts_Payperrentals_Model_Source_Excludedaysfrom::CALENDAR; ?>',
                        readOnly: false,
                        index: this.itemsCount++
                    };

                    if(arguments.length >= 5) {
                        data.website_id = arguments[0];
                        data.excludefrom      = arguments[1];
                        data.excludeto        = arguments[2];
                        data.repeatperiod      = arguments[3];
                        data.excludedaysfrom      = arguments[4];
                    }
                    if (arguments.length == 6) {
                        data.readOnly = arguments[5];
                    }

                    Element.insert($('<?php echo $_htmlId ?>_container'), {
                        bottom : this.template.evaluate(data)
                    });
                    $('excludedates_row_' + data.index + '_excludefrom').value = data.excludefrom;
                    $('excludedates_row_' + data.index + '_excludeto').value = data.excludeto;
                    $('excludedates_row_' + data.index + '_repeatperiod').value = data.repeatperiod;
                    $('excludedates_row_' + data.index + '_excludedaysfrom').value = data.excludedaysfrom;
                    $('excludedates_row_' + data.index + '_website').value    = data.website_id;

                    <?php if ($_showWebsite):?>
                    var wss = $('excludedates_row_' + data.index + '_website');
                    var txt = wss.options[wss.selectedIndex].text;

                    wss.insert({after:'<span class="website-name">' + txt + '</span>'});
                    wss.hide();
                    <?php endif;?>

                    if (data.readOnly == '1') {
                        ['website', 'excludefrom', 'excludeto', 'repeatperiod','excludedaysfrom', 'delete'].each(function(idx){
                            $('excludedates_row_'+data.index+'_'+idx).disabled = true;
                        });
                        $('excludedates_row_'+data.index+'_delete_button').hide();
                    }

                    <?php if ($_readonly): ?>
                    $('<?php echo $_htmlId ?>_container').select('input', 'select').each(this.disableElement);
                    $('<?php echo $_htmlId ?>_container').up('table').select('button').each(this.disableElement);
                    <?php else: ?>
                    $('<?php echo $_htmlId ?>_container').select('input', 'select').each(function(el){ Event.observe(el, 'change', el.setHasChanges.bind(el)); });
                    <?php endif; ?>
                },
                disableElement: function(el) {
                    el.disabled = true;
                    el.addClassName('disabled');
                },
                deleteItem: function(event) {
                    var tr = Event.findElement(event, 'tr');
                    if (tr) {
                        Element.select(tr, '.delete').each(function(elem){elem.value='1'});
                        Element.select(tr, ['input', 'select']).each(function(elem){elem.hide()});
                        Element.remove(tr);
                        //Element.addClassName(tr, 'no-display template');
                    }
                    return false;
                }
            };
            <?php foreach ($this->getValues() as $_item): ?>
            excludedDatesControl.addItem('<?php echo $_item['website_id'] ?>', '<?php echo ITwebexperts_Payperrentals_Helper_Date::formatDbDate($_item['disabled_from'], false); ?>', '<?php echo ITwebexperts_Payperrentals_Helper_Date::formatDbDate($_item['disabled_to'], false); ?>', '<?php echo $_item['disabled_type']; ?>', '<?php echo $_item['exclude_dates_from']; ?>', <?php echo (int)!empty($_item['readonly'])?>);
            <?php endforeach; ?>
            <?php if ($_readonly): ?>
			    $('<?php echo $_htmlId ?>_container').up('table').select('button').each(excludedDatesControl.disableElement);
			<?php endif; ?>
            //]]>
        </script>
    </td></tr>
