<script type="text/javascript">
    /*
     * Modify default values. Right now I don't have a faster alternative
     * */

    if($('use_global_min_qty')) {
        $('use_global_min_qty').observe("change", function (event) {
            if ($F('use_global_min_qty') == '1') {
                $('payperrentals_min_quantity').writeAttribute('readonly', 'readonly');
                $('payperrentals_min_quantity').setStyle({
                    backgroundColor: '#cccccc'
                });
            } else {
                $('payperrentals_min_quantity').removeAttribute('readonly');
                $('payperrentals_min_quantity').setStyle({
                    backgroundColor: '#ffffff'
                });
            }
        });
        $('use_global_max_qty').observe("change", function (event) {
            if ($F('use_global_max_qty') == '1') {
                $('payperrentals_max_quantity').writeAttribute('readonly', 'readonly');
                $('payperrentals_max_quantity').setStyle({
                    backgroundColor: '#cccccc'
                });
            } else {
                $('payperrentals_max_quantity').removeAttribute('readonly');
                $('payperrentals_max_quantity').setStyle({
                    backgroundColor: '#ffffff'
                });
            }
        });
    }
    $('global_min_period').observe("change", function(event) {
        if($F('global_min_period') == '1'){
            $('payperrentals_min_number').writeAttribute('readonly','readonly');
            $('payperrentals_min_number').setStyle({
                backgroundColor: '#cccccc'
            });
            $('payperrentals_min_type').setStyle({
                backgroundColor: '#cccccc'
            });
            $$('select#payperrentals_min_type option').each(function(field){
                if(!field.hasAttribute('selected')){
                    field.writeAttribute("disabled", "disabled");
                }
            });

            //$('payperrentals_min_type').writeAttribute('readonly','readonly');
        }else{
            $('payperrentals_min_number').removeAttribute('readonly');
            $('payperrentals_min_number').setStyle({
                backgroundColor: '#ffffff'
            });
            $('payperrentals_min_type').setStyle({
                backgroundColor: '#ffffff'
            });
            $$('select#payperrentals_min_type option').each(function(field){
                if(!field.hasAttribute('selected')){
                    field.removeAttribute("disabled");
                }
            });
            //$('payperrentals_min_type').removeAttribute('readonly');

        }
    });
    if($F('global_min_period') == '1'){
        $('payperrentals_min_number').writeAttribute('readonly','readonly');
        $('payperrentals_min_number').setStyle({
            backgroundColor: '#cccccc'
        });
        $('payperrentals_min_type').setStyle({
            backgroundColor: '#cccccc'
        });
        $$('select#payperrentals_min_type option').each(function(field){
            if(!field.hasAttribute('selected')){
                field.writeAttribute("disabled", "disabled");
            }
        });

    }else{
        $('payperrentals_min_number').removeAttribute('readonly');
        $('payperrentals_min_number').setStyle({
            backgroundColor: '#ffffff'
        });
        $('payperrentals_min_type').setStyle({
            backgroundColor: '#ffffff'
        });
        $$('select#payperrentals_min_type option').each(function(field){
            if(!field.hasAttribute('selected')){
                field.removeAttribute("disabled");
            }
        });

    }

    /*max period*/
    $('global_max_period').observe("change", function(event) {
        if($F('global_max_period') == '1'){
            $('payperrentals_max_number').writeAttribute('readonly','readonly');
            $('payperrentals_max_number').setStyle({
                backgroundColor: '#cccccc'
            });
            $('payperrentals_max_type').setStyle({
                backgroundColor: '#cccccc'
            });
            $$('select#payperrentals_max_type option').each(function(field){
                if(!field.hasAttribute('selected')){
                    field.writeAttribute("disabled", "disabled");
                }
            });

            //$('payperrentals_min_type').writeAttribute('readonly','readonly');
        }else{
            $('payperrentals_max_number').removeAttribute('readonly');
            $('payperrentals_max_number').setStyle({
                backgroundColor: '#ffffff'
            });
            $('payperrentals_max_type').setStyle({
                backgroundColor: '#ffffff'
            });
            $$('select#payperrentals_max_type option').each(function(field){
                if(!field.hasAttribute('selected')){
                    field.removeAttribute("disabled");
                }
            });
            //$('payperrentals_min_type').removeAttribute('readonly');

        }
    });
    if($F('global_max_period') == '1'){
        $('payperrentals_max_number').writeAttribute('readonly','readonly');
        $('payperrentals_max_number').setStyle({
            backgroundColor: '#cccccc'
        });
        $('payperrentals_max_type').setStyle({
            backgroundColor: '#cccccc'
        });
        $$('select#payperrentals_max_type option').each(function(field){
            if(!field.hasAttribute('selected')){
                field.writeAttribute("disabled", "disabled");
            }
        });

    }else{
        $('payperrentals_max_number').removeAttribute('readonly');
        $('payperrentals_max_number').setStyle({
            backgroundColor: '#ffffff'
        });
        $('payperrentals_max_type').setStyle({
            backgroundColor: '#ffffff'
        });
        $$('select#payperrentals_max_type option').each(function(field){
            if(!field.hasAttribute('selected')){
                field.removeAttribute("disabled");
            }
        });

    }

    /*turnoverbefore*/

    $('global_turnover_before').observe("change", function(event) {
        if($F('global_turnover_before') == '1'){
            $('payperrentals_avail_numberb').writeAttribute('readonly','readonly');
            $('payperrentals_avail_numberb').setStyle({
                backgroundColor: '#cccccc'
            });
            $('payperrentals_avail_typeb').setStyle({
                backgroundColor: '#cccccc'
            });
            $$('select#payperrentals_avail_typeb option').each(function(field){
                if(!field.hasAttribute('selected')){
                    field.writeAttribute("disabled", "disabled");
                }
            });

            //$('payperrentals_min_type').writeAttribute('readonly','readonly');
        }else{
            $('payperrentals_avail_numberb').removeAttribute('readonly');
            $('payperrentals_avail_numberb').setStyle({
                backgroundColor: '#ffffff'
            });
            $('payperrentals_avail_typeb').setStyle({
                backgroundColor: '#ffffff'
            });
            $$('select#payperrentals_avail_typeb option').each(function(field){
                if(!field.hasAttribute('selected')){
                    field.removeAttribute("disabled");
                }
            });
            //$('payperrentals_min_type').removeAttribute('readonly');

        }
    });
    if($F('global_turnover_before') == '1'){
        $('payperrentals_avail_numberb').writeAttribute('readonly','readonly');
        $('payperrentals_avail_numberb').setStyle({
            backgroundColor: '#cccccc'
        });
        $('payperrentals_avail_typeb').setStyle({
            backgroundColor: '#cccccc'
        });
        $$('select#payperrentals_avail_typeb option').each(function(field){
            if(!field.hasAttribute('selected')){
                field.writeAttribute("disabled", "disabled");
            }
        });

        //$('payperrentals_min_type').writeAttribute('readonly','readonly');
    }else{
        $('payperrentals_avail_numberb').removeAttribute('readonly');
        $('payperrentals_avail_numberb').setStyle({
            backgroundColor: '#ffffff'
        });
        $('payperrentals_avail_typeb').setStyle({
            backgroundColor: '#ffffff'
        });
        $$('select#payperrentals_avail_typeb option').each(function(field){
            if(!field.hasAttribute('selected')){
                field.removeAttribute("disabled");
            }
        });
        //$('payperrentals_min_type').removeAttribute('readonly');

    }

    /*turnover after*/
    $('global_turnover_after').observe("change", function(event) {
        if($F('global_turnover_after') == '1'){
            $('payperrentals_avail_number').writeAttribute('readonly','readonly');
            $('payperrentals_avail_number').setStyle({
                backgroundColor: '#cccccc'
            });
            $('payperrentals_avail_type').setStyle({
                backgroundColor: '#cccccc'
            });
            $$('select#payperrentals_avail_type option').each(function(field){
                if(!field.hasAttribute('selected')){
                    field.writeAttribute("disabled", "disabled");
                }
            });

            //$('payperrentals_min_type').writeAttribute('readonly','readonly');
        }else{
            $('payperrentals_avail_number').removeAttribute('readonly');
            $('payperrentals_avail_number').setStyle({
                backgroundColor: '#ffffff'
            });
            $('payperrentals_avail_type').setStyle({
                backgroundColor: '#ffffff'
            });
            $$('select#payperrentals_avail_type option').each(function(field){
                if(!field.hasAttribute('selected')){
                    field.removeAttribute("disabled");
                }
            });
            //$('payperrentals_min_type').removeAttribute('readonly');

        }
    });
    if($F('global_turnover_after') == '1'){
        $('payperrentals_avail_number').writeAttribute('readonly','readonly');
        $('payperrentals_avail_number').setStyle({
            backgroundColor: '#cccccc'
        });
        $('payperrentals_avail_type').setStyle({
            backgroundColor: '#cccccc'
        });
        $$('select#payperrentals_avail_type option').each(function(field){
            if(!field.hasAttribute('selected')){
                field.writeAttribute("disabled", "disabled");
            }
        });

        //$('payperrentals_min_type').writeAttribute('readonly','readonly');
    }else{
        $('payperrentals_avail_number').removeAttribute('readonly');
        $('payperrentals_avail_number').setStyle({
            backgroundColor: '#ffffff'
        });
        $('payperrentals_avail_type').setStyle({
            backgroundColor: '#ffffff'
        });
        $$('select#payperrentals_avail_type option').each(function(field){
            if(!field.hasAttribute('selected')){
                field.removeAttribute("disabled");
            }
        });
        //$('payperrentals_min_type').removeAttribute('readonly');

    }

    /*exclude days*/
    $('global_excludedays').observe("change", function(event) {

        if($F('global_excludedays') == '1'){
            $('res_excluded_daysweek').setStyle({
                backgroundColor: '#cccccc'
            });
            $$('select#res_excluded_daysweek option').each(function(field){
                if(!field.hasAttribute('selected')){
                    field.writeAttribute("disabled", "disabled");
                }
            });

        }else{
            $('res_excluded_daysweek').setStyle({
                backgroundColor: '#ffffff'
            });
            $$('select#res_excluded_daysweek option').each(function(field){
                if(!field.hasAttribute('selected')){
                    field.removeAttribute("disabled");
                }
            });
        }
    });
    if($F('global_excludedays') == '1'){
        $('res_excluded_daysweek').setStyle({
            backgroundColor: '#cccccc'
        });
        $$('select#res_excluded_daysweek option').each(function(field){
            if(!field.hasAttribute('selected')){
                field.writeAttribute("disabled", "disabled");
            }
        });

    }else{
        $('res_excluded_daysweek').setStyle({
            backgroundColor: '#ffffff'
        });
        $$('select#res_excluded_daysweek option').each(function(field){
            if(!field.hasAttribute('selected')){
                field.removeAttribute("disabled");
            }
        });
    }
    /*End modify default value*/

    /*use global exclude dates*/
    $('use_global_exclude_dates').observe("change", function(event) {
        //$jppr('#payperrentals_use_serials').change(function(){
        if($F('use_global_exclude_dates') == '1'){
            $$('table#excludedates_table button').each(function(field){
                field.writeAttribute('disabled', 'disabled');
                if(!field.hasClassName('disabled')){
                    field.toggleClassName('disabled');
                }

            });

            $$('table#excludedates_table input').each(function(field){
                field.writeAttribute('readonly', 'readonly');
            });

        }else{

            $$('table#excludedates_table button').each(function(field){
                if(field.hasAttribute('disabled')){
                    field.removeAttribute("disabled");
                }
                //field.removeAttribute('disabled');
                if(field.hasClassName('disabled')){
                    field.toggleClassName('disabled');
                }
            });

            $$('table#excludedates_table input').each(function(field){
                if(field.hasAttribute('readonly')){
                    field.removeAttribute('readonly');
                }
            });

        }
    });
    triggerEventProtoype($('use_global_exclude_dates'),'change');
    <?php  if(Mage::registry('current_product')->getTypeId() == 'reservation'): ?>
    $('table_cataloginventory').hide();
    <?php endif; ?>
    //$('inventory_use_config_manage_stock').checked = false;
    //toggleValueElements($('inventory_use_config_manage_stock'), $('inventory_use_config_manage_stock').parentNode);
    //$('inventory_manage_stock').select('option')[1].selected = true;

    if($('inventory_min_sale_qty')) {
        $('inventory_min_sale_qty').up('tr').hide();
        $('inventory_max_sale_qty').up('tr').hide();
        $('original_inventory_qty').up('tr').hide();
        $('original_inventory_qty').up('tr').setStyle({
            visibility: 'hidden'
        })
    }

    p = 0;
    $$('[title^="Inventory"]').each( function(i) {
        p++;
        if(p == 1) {
            document.getElementById(i.id+'_content').getElementsByClassName('fieldset')[0].appendChild(
                document.getElementById('product_info_tabs_inventory_content').getElementsByTagName("table")[0]
            );

        }else{
            document.getElementById(i.id).hide();
        }
    });
    /**/
    <?php
			if(Mage::app()->getRequest()->getParam('detailsonly')){
			?>
    $jppr('#product_info_tabs li a.tab-item-link').hide();
    $jppr('.header').hide();
    $jppr('#product_info_tabs li a[title="General"]').show();
    $jppr('#product_info_tabs_Payperrentals').show();

    <?php
    }
    ?>
    <?php
    if(Mage::app()->getRequest()->getControllerName() == 'catalog_product' && Mage::app()->getRequest()->getActionName() == 'edit'){
    ?>
    if($F('is_reservation') == ''){
        $('is_reservation').value = '5';
    }
    if($F('payperrentals_quantity') == ''){
        $('payperrentals_quantity').value = '1';
    }

    <?php
    }
    ?>
</script>