<?php

?>
<?php

$_htmlId = $this->getElement()->getHtmlId() ?>
<?php $_htmlClass = $this->getElement()->getClass() ?>
<?php $_htmlName = $this->getElement()->getName() ?>
<?php $_readonly = $this->getElement()->getReadonly() ?>
<?php $_storeId = $this->getProduct()->getStoreId() ?>
<?php $_showWebsite = 0 && !Mage::app()->isSingleStoreMode() ?>
<?php $_priceValueValidation = $this->getPriceValidation('validate-greater-than-zero'); ?>


<tr>
<td class="label"><?php echo $this->getElement()->getLabel() ?></td>
<td colspan="11" class="grid reservationprices">
<?php echo Mage::helper('payperrentals')->__('Example:<br /><b>Number of:</b> 2 <b>Period Type:</b> Week <b>Price:</b> $5 <b>Additional Type:</b> Day <b>Additional Price:</b> $2<br />This would mean 2 Weeks is $5 and each additional day is $2') ?>
<table cellspacing="0" class="data border" id="reservationprices_table">
    <?php if ($_showWebsite): ?>
        <col width="135"/>
    <?php endif; ?>
    <col width="120"/>
    <col width="95"/>
    <col/>
    <col/>
    <col/>
    <thead>
    <tr class="headings">
        <th <?php if (!$_showWebsite): ?>style="display:none"<?php endif; ?>><?php echo Mage::helper('payperrentals')->__('Website') ?></th>
        <th><?php echo Mage::helper('payperrentals')->__('Number of') ?></th>
        <th><?php echo Mage::helper('payperrentals')->__('Period Type') ?></th>
        <th><?php echo Mage::helper('payperrentals')->__('Price') ?></th>
        <th><?php echo Mage::helper('payperrentals')->__('Damage Waiver') ?></th>
        <th><?php echo Mage::helper('payperrentals')->__('Applies To') ?></th>
<!--        <th>--><?php //echo Mage::helper('payperrentals')->__('Date Start') ?><!--</th>-->
<!--        <th>--><?php //echo Mage::helper('payperrentals')->__('Date end') ?><!--</th>-->
        <th><?php echo Mage::helper('payperrentals')->__('Additional Type') ?></th>
        <th><?php echo Mage::helper('payperrentals')->__('Additional Price') ?></th>
        <th><?php echo Mage::helper('payperrentals')->__('Qty Start') ?></th>
        <th><?php echo Mage::helper('payperrentals')->__('Qty End') ?></th>
        <th><?php echo Mage::helper('payperrentals')->__('Customers Group') ?></th>
        <th <?php if (!$_storeId): ?>style="display:none"<?php endif; ?>>Use Default</th>
        <th class="last"><?php echo Mage::helper('payperrentals')->__('Action') ?></th>
    </tr>
    </thead>
    <tbody id="<?php echo $_htmlId ?>_container"></tbody>
    <tfoot>
    <tr>
        <td <?php if (!$_showWebsite): ?>style="display:none"<?php endif; ?>></td>
        <td colspan="11" class="a-right"><?php echo $this->getChildHtml('add_button'); ?></td>
    </tr>
    </tfoot>
</table>
<?php
/** setup reservation prices & dates drop down */
$reservationpricesdatesColl = Mage::getModel('payperrentals/reservationpricesdates')->getCollection();
$htmloptions = "<option value=\"0\" selected=\"selected\">" . Mage::helper('payperrentals')->__('Any Date/Time') . "</option>";
foreach($reservationpricesdatesColl as $respricedateItem)
{
    $htmloptions .= "<option value=" . $respricedateItem->getId() . ">" . $respricedateItem->getDescription() . "</option>";
}
$htmloptions .= "</select>";
?>
<script type="text/javascript">
//<![CDATA[
var reservationPricesRowTemplate = '<tr>'
    + '<td<?php if (!$_showWebsite): ?> style="display:none"<?php endif; ?>>'
    + '<select class="<?php echo $_htmlClass ?>" name="<?php echo $_htmlName ?>[{{index}}][website_id]" id="reservationprices_row_{{index}}_website">'
    <?php foreach ($this->getWebsites() as $_websiteId => $_info): ?>
    + '<option value="<?php echo $_websiteId ?>"><?php echo $this->jsQuoteEscape($this->htmlEscape($_info['name'])) ?><?php if (!empty($_info['currency'])): ?> [<?php echo $this->htmlEscape($_info['currency']) ?>]<?php endif; ?></option>'
    <?php endforeach ?>
    + '</select></td>'
    + '<td class="nobr"><input type="text" size="3" class="required-entry validate-greater-than-zero" name="<?php echo $_htmlName ?>[{{index}}][numberof]" id="reservationprices_row_{{index}}_numberof"/></td>'
    + '<td><select class="<?php echo $_htmlClass ?> ptype required-entry" name="<?php echo $_htmlName ?>[{{index}}][ptype]" id="reservationprices_row_{{index}}_ptype">'
    + '<option value="<?php echo ITwebexperts_Payperrentals_Model_Product_Periodtype::MINUTES;?>"><?php echo Mage::helper('catalog')->__('Minutes');?></option>'
    + '<option value="<?php echo ITwebexperts_Payperrentals_Model_Product_Periodtype::HOURS;?>"><?php echo Mage::helper('catalog')->__('Hours');?></option>'
    + '<option value="<?php echo ITwebexperts_Payperrentals_Model_Product_Periodtype::DAYS;?>"><?php echo Mage::helper('catalog')->__('Days');?></option>'
    + '<option value="<?php echo ITwebexperts_Payperrentals_Model_Product_Periodtype::WEEKS;?>"><?php echo Mage::helper('catalog')->__('Weeks');?></option>'
    + '<option value="<?php echo ITwebexperts_Payperrentals_Model_Product_Periodtype::MONTHS;?>"><?php echo Mage::helper('catalog')->__('Months');?></option>'
    + '<option value="<?php echo ITwebexperts_Payperrentals_Model_Product_Periodtype::YEARS;?>"><?php echo Mage::helper('catalog')->__('Years');?></option>'
    <?php //endforeach ?>
    + '</select></td>'
    + '<td class="nobr"><input type="text" size="5" class="required-entry validate-zero-or-greater" name="<?php echo $_htmlName ?>[{{index}}][price]" id="reservationprices_row_{{index}}_price"/></td>'
    + '<td class="nobr"><input type="text" size="5" class="validate-zero-or-greater" name="<?php echo $_htmlName ?>[{{index}}][damage_waiver]" id="reservationprices_row_{{index}}_damage_waiver"/> %</td>'
    + '<td class="nobr"><select name="<?php echo $_htmlName ?>[{{index}}][reservationpricesdates_id]" id="reservationprices_row_{{index}}_reservationpricesdates_id"><?php echo $htmloptions ?></td>'
    //+ '<td class="nobr"><?php //echo $this->makeDateTimeBlock($_htmlName, 'datefrom') ?></td>'
    //+ '<td class="nobr"><?php //echo $this->makeDateTimeBlock($_htmlName, 'dateto') ?></td>'
    + '<td><select class="<?php echo $_htmlClass ?> ptypeadditional required-entry" name="<?php echo $_htmlName ?>[{{index}}][ptypeadditional]" id="reservationprices_row_{{index}}_ptypeadditional">'
    + '<option value="<?php echo ITwebexperts_Payperrentals_Model_Product_Periodtype::MINUTES;?>"><?php echo Mage::helper('catalog')->__('Minute');?></option>'
    + '<option value="<?php echo ITwebexperts_Payperrentals_Model_Product_Periodtype::HOURS;?>"><?php echo Mage::helper('catalog')->__('Hour');?></option>'
    + '<option value="<?php echo ITwebexperts_Payperrentals_Model_Product_Periodtype::DAYS;?>"><?php echo Mage::helper('catalog')->__('Day');?></option>'
    + '<option value="<?php echo ITwebexperts_Payperrentals_Model_Product_Periodtype::WEEKS;?>"><?php echo Mage::helper('catalog')->__('Week');?></option>'
    + '<option value="<?php echo ITwebexperts_Payperrentals_Model_Product_Periodtype::MONTHS;?>"><?php echo Mage::helper('catalog')->__('Month');?></option>'
    + '<option value="<?php echo ITwebexperts_Payperrentals_Model_Product_Periodtype::YEARS;?>"><?php echo Mage::helper('catalog')->__('Year');?></option>'
    <?php //endforeach ?>
    + '</select></td>'
    + '<td class="nobr"><input type="text" size="5" class="" name="<?php echo $_htmlName ?>[{{index}}][priceadditional]" id="reservationprices_row_{{index}}_priceadditional"/></td>'
    + '<td class="nobr"><input type="text" size="3" class="validate-zero-or-greater" name="<?php echo $_htmlName ?>[{{index}}][qtystart]" id="reservationprices_row_{{index}}_qtystart"/></td>'
    + '<td class="nobr"><input type="text" size="3" class="validate-zero-or-greater" name="<?php echo $_htmlName ?>[{{index}}][qtyend]" id="reservationprices_row_{{index}}_qtyend"/></td>'

    + '<td><select class="<?php echo $_htmlClass ?> custgroup required-entry" name="<?php echo $_htmlName ?>[{{index}}][custgroup]" id="reservationprices_row_{{index}}_custgroup">'
    + '<option value="<?php echo '-1';?>"><?php echo Mage::helper('catalog')->__('Any');?></option>'
    <?php foreach ($this->getCustomerGroups() as $_groupId=>$_groupName): ?>
    + '<option value="<?php echo $_groupId ?>"><?php echo $this->jsQuoteEscape($this->htmlEscape($_groupName)) ?></option>'
    <?php endforeach ?>
    + '</select></td>'
    + '<td <?php if (!$_storeId): ?>style="display:none"<?php endif; ?> class="nobr">'
    + '<input type="checkbox" name="<?php echo $_htmlName ?>[{{index}}][use_default_value]" id="reservationprices_row_{{index}}_use_default_value"/> </td>'
    + '<td class="last"><input type="hidden" name="<?php echo $_htmlName ?>[{{index}}][delete]" class="delete" value="" id="reservationprices_row_{{index}}_delete" />'
    + '<button title="<?php echo Mage::helper('catalog')->__("Delete Tier") ?>" type="button" class="scalable delete icon-btn delete-product-option" id="reservationprices_row_{{index}}_delete_button" onclick="return reservationPricesControl.deleteItem(event);">'
    + '<span><span><span><?php echo Mage::helper('catalog')->__("Delete") ?></span></span></span></button></td>'
    + '</tr>';

var reservationPricesControl = {
    template: new Template(reservationPricesRowTemplate, new RegExp('(^|.|\\r|\\n)({{\\s*(\\w+)\\s*}})', "")),
    itemsCount: 0,
    defaultStoreId:<?php echo $_storeId;?>,
    addItem: function () {
        <?php if ($_readonly): ?>
        if (arguments.length < 4) {
            return;
        }
        <?php endif; ?>
        var data = {
            website_id: '<?php echo $this->getDefaultWebsite() ?>',
            numberof: '<?php echo '1'; ?>',
            ptype: '',
            price: '',
            reservationpricesdates_id: '0',
            datefrom: '',
            dateto: '',
            ptypeadditional: '',
            priceadditional: '',
            qtystart: '',
            qtyend: '',
            custgroup: '-1',
            store_id: '<?php echo $_storeId; ?>',
            readOnly: false,
            damage_waiver: '0',
            index: this.itemsCount++
        };

        if (arguments.length >= 9) {
            data.website_id = arguments[0];
            data.numberof = arguments[1];
            data.ptype = arguments[2];
            data.price = arguments[3];
            data.reservationpricesdates_id = arguments[4],
            //data.datefrom = arguments[4];
            //data.dateto = arguments[5];
            data.ptypeadditional = arguments[5];
            data.priceadditional = arguments[6];
            data.qtystart = arguments[7];
            data.qtyend = arguments[8];
            data.custgroup = arguments[9];
            data.store_id = arguments[10];
            data.damage_waiver = arguments[11]
        }

        if (arguments.length == 11) {
            data.readOnly = arguments[12];
        }

        Element.insert($('<?php echo $_htmlId ?>_container'), {
            bottom: this.template.evaluate(data)
        });
        $('reservationprices_row_' + data.index + '_numberof').value = data.numberof;
        //$('reservationprices_row_' + data.index + '_ptype').value = data.ptype;
        $$('select#' + 'reservationprices_row_' + data.index + '_ptype' + ' option').each(function (o) {

            if (o.readAttribute('value') == data.ptype) {
                o.selected = true;
                o.writeAttribute('selected', 'selected');
            }
        });
        $$('select#' + 'reservationprices_row_' + data.index + '_ptypeadditional' + ' option').each(function (o) {

            if (o.readAttribute('value') == data.ptypeadditional) {
                o.selected = true;
                o.writeAttribute('selected', 'selected');
            }
        });
        $$('select#' + 'reservationprices_row_' + data.index + '_reservationpricesdates_id' + ' option').each(function (o) {

            if (o.readAttribute('value') == data.reservationpricesdates_id) {
                o.selected = true;
                o.writeAttribute('selected', 'selected');
            }
        });
        $('reservationprices_row_' + data.index + '_price').value = data.price;
        //$('reservationprices_row_' + data.index + '_datefrom').value = data.datefrom;
        //$('reservationprices_row_' + data.index + '_dateto').value = data.dateto;
        $('reservationprices_row_' + data.index + '_reservationpricesdates_id').value = data.reservationpricesdates_id;
        $('reservationprices_row_' + data.index + '_priceadditional').value = data.priceadditional;
        $('reservationprices_row_' + data.index + '_qtystart').value = data.qtystart;
        $('reservationprices_row_' + data.index + '_qtyend').value = data.qtyend;
        $('reservationprices_row_' + data.index + '_custgroup').value = data.custgroup;
        $$('select#' + 'reservationprices_row_' + data.index + '_custgroup' + ' option').each(function (o) {
            if (o.readAttribute('value') == data.custgroup) {
                o.selected = true;
                o.writeAttribute('selected', 'selected');
            }
            //o.selected = o.readAttribute('value') == data.custgroup;
        });
        $('reservationprices_row_' + data.index + '_website').value = data.website_id;
        $('reservationprices_row_' + data.index + '_damage_waiver').value = data.damage_waiver;

        $('reservationprices_row_' + data.index + '_use_default_value').setValue(data.store_id == 0);
        if (data.store_id && (typeof arguments[9] == 'undefined')) {
            $($('reservationprices_row_' + data.index + '_use_default_value').parentNode).style.visibility = 'hidden';
        }

        $('reservationprices_row_' + data.index + '_use_default_value').onclick = function () {
            if (this.checked) {
                $(this.parentNode.parentNode).select('input', 'select')
                    .each(reservationPricesControl.disableElement);

            } else {
                $(this.parentNode.parentNode).select('input', 'select')
                    .each(reservationPricesControl.enableElement);
            }

        };

        if (data.store_id == '0' && parseInt(this.defaultStoreId)) {
            $($('reservationprices_row_' + data.index + '_use_default_value').parentNode.parentNode)
                .select('input', 'select')
                .each(reservationPricesControl.disableElement);

        }

        $('reservationprices_row_' + data.index + '_use_default_value').disabled = false;
        $('reservationprices_row_' + data.index + '_use_default_value').removeClassName('disabled');

        <?php if ($_showWebsite):?>
        var wss = $('reservationprices_row_' + data.index + '_website');
        var txt = wss.options[wss.selectedIndex].text;

        wss.insert({after: '<span class="website-name">' + txt + '</span>'});
        wss.hide();
        <?php endif;?>

        if (data.readOnly == '1') {
            ['website', 'numberof', 'ptype', 'price', 'datefrom', 'dateto','ptypeadditional','priceadditional','qtystart', 'qtyend', 'custgroup', 'delete'].each(function (idx) {
                $('reservationprices_row_' + data.index + '_' + idx).disabled = true;
            });
            $('reservationprices_row_' + data.index + '_delete_button').hide();
        }

        <?php if ($_readonly): ?>
        $('<?php echo $_htmlId ?>_container').select('input', 'select').each(this.disableElement);
        $('<?php echo $_htmlId ?>_container').up('table').select('button').each(this.disableElement);
        <?php else: ?>
        $('<?php echo $_htmlId ?>_container').select('input', 'select').each(function (el) {
            Event.observe(el, 'change', el.setHasChanges.bind(el));
        });
        <?php endif; ?>
    },
    disableElement: function (el) {
        el.readOnly = true;
        el.addClassName('disabled');
        el.setStyle({
            backgroundColor: '#cccccc'
        });
        $$('select#' + el.id + ' option').each(function (field) {
            if (!field.hasAttribute('selected')) {
                field.writeAttribute("disabled", "disabled");
            }
        });
    },
    enableElement: function (el) {
        el.readOnly = false;
        el.removeClassName('disabled');
        el.setStyle({
            backgroundColor: '#ffffff'
        });
        $$('select#' + el.id + ' option').each(function (field) {
            if (!field.hasAttribute('selected')) {
                field.removeAttribute("disabled");
            }
        });
    },
    deleteItem: function (event) {
        var tr = Event.findElement(event, 'tr');
        if (tr) {
            Element.select(tr, '.delete').each(function (elem) {
                elem.value = '1'
            });
            Element.select(tr, ['input', 'select']).each(function (elem) {
                elem.hide()
            });
            Element.remove(tr);
            //Element.addClassName(tr, 'no-display template');
        }
        return false;
    }
};
<?php foreach ($this->getValues() as $_item): ?>
reservationPricesControl.addItem('<?php echo $_item['website_id'] ?>', '<?php echo $_item['numberof']; ?>', '<?php echo $_item['ptype']; ?>', '<?php echo $_item['price']; ?>', '<?php echo $_item['reservationpricesdates_id']; ?>', '<?php echo $_item['ptypeadditional']; ?>','<?php echo $_item['priceadditional']; ?>','<?php echo $_item['qty_start']; ?>', '<?php echo $_item['qty_end']; ?>', '<?php echo $_item['customers_group']; ?>', '<?php echo $_item['store_id'] ?>', <?php echo $_item['damage_waiver'] ?>, <?php echo (int)!empty($_item['readonly'])?>);
<?php endforeach; ?>
<?php if ($_readonly): ?>
$('<?php echo $_htmlId ?>_container').up('table').select('button')
    .each(reservationPricesControl.disableElement);
<?php endif; ?>
//]]>
</script>
</td>
</tr>
