<?php if (
!$this->getProduct() || // If no product don't show rental calendar
!$this->getProduct()->isSalable() || // If product is not saleable, don't show rental calendar
    // If is_reservation is set to rental membership, don't show rental calendar
    $this->getProduct()->getIsReservation() == ITwebexperts_Payperrentals_Model_Product_Isreservation::STATUS_RENTAL ||
    // If is_reservatin is disabled, don't show rental calendar
    $this->getProduct()->getIsReservation() == ITwebexperts_Payperrentals_Model_Product_Isreservation::STATUS_DISABLED ||
    // If is_reservation is not set, don't show rental calendar
    $this->getProduct()->getIsReservation() == ITwebexperts_Payperrentals_Model_Product_Isreservation::STATUS_NOTSET
) { return; } ?>
<?php $_product = $this->getProduct(); ?>
<?php
/** @var $_configHelper ITwebexperts_Payperrentals_Helper_Config */
$_configHelper = Mage::helper('payperrentals/config');
?>
    <div class="reservationCalendarDiv">
        <?php if ($_product->getTypeId() == ITwebexperts_Payperrentals_Helper_Data::PRODUCT_TYPE_GROUPED): ?>
            <div class="price-box">
              <span class="regular-price" id="product-price-<?php echo $_product->getId() . $_jsFunctionPrefix; ?>">
                 <span class="price" style="display: inline;"></span>
              </span>
            </div>
        <?php elseif ($_product->getTypeId() != ITwebexperts_Payperrentals_Helper_Data::PRODUCT_TYPE_BUNDLE): ?>
             <?php echo $this->getChildHtml('product-price'); ?>
        <?php endif; ?>

        <?php if ($this->getChild('product-shipping')): ?>
            <?php echo $this->getChildHtml('product-shipping'); ?>
        <?php endif; ?>
        <div class="calendarTable">
            <div class="priceList">
                <?php if($_configHelper->showMinMaxProductDetailsPage()):?>
                <div class="minmaxPeriod">
                    <?php if ($_minRentalPeriod > 0) echo $this->__('Minimum Period') . ': ' . $_minRentalMessageText; ?>
                    <?php if ($_maxRentalPeriod > 0) echo '<br/>' . $this->__('Maximum Period') . ': ' . $_maxRentalMessageText; ?>
                </div>
                <?php endif; ?>

                <div class="normalPrice">
                    <?php
                    echo ITwebexperts_Payperrentals_Helper_Price::getPriceListHtml($_product,Mage::helper('payperrentals/config')->showPrice()); ?>
                </div>

                <?php if (floatval($_product->getPayperrentalsDeposit()) > 0): ?>
                    <div class="depositPrice" style="margin-bottom:20px;">
                        <?php echo '<b>' . $this->__('Deposit Amount: ') . '</b>' . Mage::helper('core')->currency(floatval($_product->getPayperrentalsDeposit())); ?>
                    </div>
                <?php endif; ?>
                <?php if ($_selectedArray !== false): ?>
                    <div class="selectedDays">
                        <?php $_p = 0; ?>
                        <?php foreach ($_selectedArray as $_iDay): ?>
                            <?php echo '<input type="radio" class="selectedDayRadio" name="selDays" value="' . $_iDay . '"' . ($_p == 0 ? 'checked="checked"' : '') . ' />' . $_iDay . ' ' . $this->__('days') . '<br/>'; ?>
                            <?php $_p++; ?>
                        <?php endforeach; ?>
                    </div>
                <?php endif; ?>
            </div>

            <div class="qty-move-container"></div>

            <div class="reservationInfo"></div>
            <?php if(!ITwebexperts_Payperrentals_Helper_Data::isUsingGlobalDates() || Mage::registry('current_product') && Mage::helper('payperrentals/config')->showCalendarOnProductInfo()): ?>
            <h4 class="chooseDatesLabel"><?php echo $this->__('Choose Your Reservation Dates') ?></h4>
            <?php echo $this->getCalendar(); ?>
                <?php else: ?>
                <?php
                $_productId = $this->getProduct()->getId();
                $_fixedRentalDates = ITwebexperts_Payperrentals_Helper_Data::getFixedRentalDates($_productId);
                $_fixedRentalDates = ITwebexperts_Payperrentals_Helper_Data::toFormattedArraysOfDatesArray($_fixedRentalDates, false);
                ?>
                <?php if (count($_fixedRentalDates) > 0) :?>
                    <input type="hidden" class="pprproductid" value="<?php echo $this->getProduct()->getId();?>"/>
                <?php endif; ?>
            <?php endif; ?>
        </div>
    </div>
