<?php
/*!
 * Theme Name: JM Team
 * Theme URI: http://www.joomlart.com
 * Version: 1.0
 * Description: 
 * Author: JM Team - Joomlart.com
 * Author URI: http://www.joomlart.com
 * 
 * Powered by Magento
 * Licensed under the Apache License v2.0
 * http://www.apache.org/licenses/LICENSE-2.0
 * Template for Mage_Page_Block_Html
 */
?>
<div class="jm-info clearfix">
  <?php echo $this->getChildHtml() ?>
</div>
<div class="jm-legal">
	<p id="flogo"><a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" style="background-image: url(<?php echo $this->getSkinUrl('images/flogo.png') ?>);"><?php echo $this->getLogoAlt() ?></a></p>
	<?php echo $this->getCopyright() ?>
	Powered by <a href="http://www.joomlart.com/magento/themes/jm-travelgear" title="JM Travelgear" rel="nofollow">JM Travelgear</a> - Designed by JoomlArt.com
</div>
