<?php
/*!
 * Theme Name: JM Team
 * Theme URI: http://www.joomlart.com
 * Version: 1.0
 * Description:
 * Author: JM Team - Joomlart.com
 * Author URI: http://www.joomlart.com
 *
 * Powered by Magento
 * Licensed under the Apache License v2.0
 * http://www.apache.org/licenses/LICENSE-2.0
 * Template for Mage_Page_Block_Html
 */
 $baseconfig =  Mage::helper("jmbasetheme")->getactiveprofile();
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $this->getLang() ?>" lang="<?php echo $this->getLang() ?>">
<!--[if IE]>
<html class="ie" xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $this->getLang() ?>" lang="<?php echo $this->getLang() ?>">
<![endif]-->
<!--[if IE 8]>
<html class="ie8" xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $this->getLang() ?>" lang="<?php echo $this->getLang() ?>">
<![endif]-->
<!--[if IE 9]>
<html class="ie9" xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $this->getLang() ?>" lang="<?php echo $this->getLang() ?>">
<![endif]-->
<!--[if IE 10]>
<html class="ie10" xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $this->getLang() ?>" lang="<?php echo $this->getLang() ?>">
<![endif]-->
<head>
<?php echo $this->getChildHtml('head') ?>
</head>
<body id="bd" class="<?php echo 'skin-'.Mage::helper("jmbasetheme")->getprofile(); ?><?php echo $this->getBodyClass();?> locate-<?php echo $this->getLang() ?>">
<?php echo $this->getChildHtml('after_body_start') ?>
<div id="jm-wrapper">
	<!-- BEGIN: HEADER -->
	<div id="jm-header" class="wrap clearfix">
		<?php echo $this->getChildHtml('header') ?>
	</div>
	<!-- END: HEADER -->
	<?php if($baseconfig["urlfacebook"] || $baseconfig["urltwitter"] || $baseconfig["urlgoogleplus"] || $baseconfig["urlpinterest"] || $baseconfig["urltumblr"] || $baseconfig["urlskype"]): ?>
		<div class="sidebar-socials">
			<?php if($baseconfig["urlfacebook"]): ?>
			<a href="<?php echo $baseconfig["urlfacebook"]; ?>" class="fa fa-facebook facebook"></a>
			<?php endif; ?>
			<?php if($baseconfig["urltwitter"]): ?>
			<a href="<?php echo $baseconfig["urltwitter"]; ?>" class="fa fa-twitter twitter"></a>
			<?php endif; ?>
			<?php if($baseconfig["urlgoogleplus"]): ?>
			<a href="<?php echo $baseconfig["urlgoogleplus"]; ?>" class="fa fa-google-plus google-plus"></a>
			<?php endif; ?>
			<?php if($baseconfig["urlpinterest"]): ?>
			<a href="<?php echo $baseconfig["urlpinterest"]; ?>" class="fa fa-pinterest pinterest"></a>
			<?php endif; ?>
			<?php if($baseconfig["urltumblr"]): ?>
			<a href="<?php echo $baseconfig["urltumblr"]; ?>" class="fa fa-tumblr tumblr"></a>
			<?php endif; ?>
			<?php if($baseconfig["urlskype"]): ?>
			<a href="skype:<?php echo $baseconfig["urlskype"]; ?>?call" class="fa fa-skype skype"></a>
			<?php endif; ?>
		</div>
	<?php endif; ?>
	<?php if ($this->getChildHtml('tops1')) : ?>
	<!-- TOP SPOTLIGHT -->
	<div id="jm-tops1" class="wrap clearfix">
		<?php echo $this->getChildHtml('tops1') ?>
	</div>
	<!-- //TOP SPOTLIGHT -->
	<?php endif; ?>
	<?php if ($this->getChildHtml('tops2')) : ?>
	<!-- //TOP SPOTLIGHT 2 -->
	<div id="jm-tops2" class="wrap clearfix">
		<div class="main col3-set">
			<?php echo $this->getChildHtml('tops2') ?>
		</div>
	</div>
	<!-- //TOP SPOTLIGHT 2 -->
	<?php endif; ?>
	<?php if ($this->getChildHtml('tops3')) : ?>
	<!-- //TOP SPOTLIGHT 3 -->
	<div id="jm-tops3" class="wrap clearfix">
		<div class="main col1-set">
			<?php echo $this->getChildHtml('tops3') ?>
		</div>
	</div>
	<!-- //TOP SPOTLIGHT 3 -->
	<?php endif; ?>
	<?php if ($this->getChildHtml('mass-top')) : ?>
	<!-- //TOP MASS -->
	<div id="jm-mass-top" class="jm-mass-top wrap clearfix">
		<div class="main col1-set">
			<?php echo $this->getChildHtml('mass-top') ?>
		</div>
	</div>
	<!-- //TOP MASS -->
	<?php endif; ?>
	<?php if ($this->getChildHtml('breadcrumbs')) : ?>
	<!-- breadcrumbs -->
	<div id="jm-breadcrumbs" class="wrap <?php if (!$this->getChildHtml('mass-head')) : ?>not-mass-head<?php endif; ?> clearfix">
		<div class="main clearfix">
			<?php echo $this->getChildHtml('breadcrumbs') ?>
		</div>
	</div>
	<!-- // breadcrumbs -->
	<?php endif; ?>
	<?php if($this->getChildHtml('global_messages') || $this->getChildHtml('messages')) :?>
	<!-- global messages -->
	<div id="jm-messages" class="wrap clearfix">
		<div class="main clearfix">
			<div class="inner clearfix">
				<?php echo $this->getChildHtml('global_messages') ?>
				<?php echo $this->getChildHtml('messages') ?>
			</div>
		</div>
	</div>
	<!-- // global messages -->
	<?php endif; ?>
	<!-- BEGIN: MAIN CONTAINER -->
	<div id="jm-container" class="jm-col1-layout <?php if ($this->getChildHtml('mass-head')) : ?>show-mass-head<?php endif; ?><?php if(!$this->getChildHtml('breadcrumbs')) { echo "not-breadcrumbs"; }?> wrap clearfix">
		<div class="main clearfix">
			<div id="jm-mainbody" class="clearfix">
				<!-- BEGIN: CONTENT -->
				<div id="jm-main">
					<?php if ($this->getChildHtml('mass-head')) : ?>
					<div id="jm-mass-head" class="jm-mass-head">
					  	<?php echo $this->getChildHtml('mass-head') ?>
					</div>
					<?php endif; ?>
					<div id="jm-current-content" class="clearfix">
					  <?php echo $this->getChildHtml('content') ?>
					</div>
				</div>
				<!-- END: CONTENT -->
			</div>
		</div>
	</div>
	<!-- END: MAIN CONTAINER -->
	<?php if ($this->getChildHtml('mass-bottom')) : ?>
	<!-- //BOTTOM SPOTLIGHT -->
	<div id="jm-mass-bottom" class="jm-mass-bottom wrap clearfix">
		<div class="main col3-set">
			<?php echo $this->getChildHtml('mass-bottom') ?>
		</div>
	</div>
	<!-- //BOTTOM SPOTLIGHT -->
	<?php endif; ?>
	<?php if ($this->getChildHtml('bots1')) : ?>
	<!-- BOTTOM SPOTLIGHT -->
	<div id="jm-bots1" class="jm-spotlight wrap clearfix">
		<div class="main col2-set clearfix">
			<?php echo $this->getChildHtml('bots1') ?>
	  </div>
	</div>
	<!-- //BOTTOM SPOTLIGHT -->
	<?php endif; ?>
	<?php if ($this->getChildHtml('bots2')) : ?>
	<!-- BOTTOM SPOTLIGHT -->
	<div id="jm-bots2" class="wrap clearfix">
		<div class="main col1-set clearfix">
		<?php echo $this->getChildHtml('bots2') ?>
	  </div>
	</div>
	<!-- //BOTTOM SPOTLIGHT -->
	<?php endif; ?>
	<?php if ($this->getChildHtml('bots3')) : ?>
	<!-- BOTTOM SPOTLIGHT -->
	<div id="jm-bots3" class="wrap clearfix">
		<div class="main col1-set clearfix">
			<?php echo $this->getChildHtml('bots3') ?>
	  </div>
	</div>
	<!-- //BOTTOM SPOTLIGHT -->
	<?php endif; ?>
	<!-- BEGIN: FOOTER -->
	<div id="jm-footer" class="wrap clearfix">
		<div class="main">
			<?php echo $this->getChildHtml('footer') ?>
		</div>
	</div>
	<!-- END: FOOTER -->
	<?php echo $this->getChildHtml('before_body_end') ?>
</div>
<?php echo $this->getAbsoluteFooter() ?>
</body>
</html>
