<html><head>
    {{var stylesheet}}
</head><body>
<p><br /><img src="{{var logourl}}"><br /><br /></p>
<h3>{{var contracttitle}}</h3><br/>
{{var headertext}}
<table cellpadding="5" cellspacing="0" border="1" >
<!--    <tr>-->
<!--        <td>-->
<!--            <table cellpadding="20" cellspacing="0" border="0" >-->
<!--                <tr>-->
<!--                    <td class="email-heading" valign="top" >-->
<!--                        <h1>Thank you for your order from {{var store.getFrontendName()}}.</h1>-->
<!--                        <p>Once your package ships we will send an email with a link to track your order. Your order summary is below. Thank you again for your business.</p>-->
<!--                    </td>-->
<!--                    <td valign="top" class="store-info">-->
<!--                        <h4>Order Questions?</h4>-->
<!--                        <p>-->
<!--                            {{depend store_phone}}-->
<!--                            <b>Call Us:</b>-->
<!--                            <a href="tel:{{var phone}}">{{var store_phone}}</a><br>-->
<!--                            {{/depend}}-->
<!--                            {{depend store_hours}}-->
<!--                            <span class="no-link">{{var store_hours}}</span><br>-->
<!--                            {{/depend}}-->
<!--                            {{depend store_email}}-->
<!--                            <b>Email:</b> <a href="mailto:{{var store_email}}">{{var store_email}}</a>-->
<!--                            {{/depend}}-->
<!--                        </p>-->
<!--                    </td>-->
<!--                </tr>-->
<!--            </table>-->
<!--        </td>-->
<!--    </tr>-->
    <tr>
        <td class="order-details">
            <h3>Your order <span class="no-link">#{{var order.increment_id}}</span></h3>
            <p>Placed on {{var order.getCreatedAtFormated('long')}}</p>
        </td>
    </tr>
    <tr>
        <td class="order-details">
    {{layout handle="sales_pdf_order_items" order=$order}}
        </td>
    </tr>
    <tr class="order-information">
        <td>
            {{if order.getEmailCustomerNote()}}
            <table cellspacing="0" cellpadding="0" class="message-container">
                <tr>
                    <td>{{var order.getEmailCustomerNote()}}</td>
                </tr>
            </table>
            {{/if}}

            <table cellpadding="0" cellspacing="0" border="0">
                <tr>
                    <td class="address-details">
                        <h6 class="big">Bill to:</h6>
                        <p><span class="no-link">{{var order.getBillingAddress().format('html')}}</span></p>
                    </td>
                    {{depend order.getIsNotVirtual()}}
                    <td class="address-details">
                        <h6 class="big">Ship to:</h6>
                        <p><span class="no-link">{{var order.getShippingAddress().format('html')}}</span></p>
                    </td>
                    {{/depend}}
                </tr>
                <tr>
                    {{depend order.getIsNotVirtual()}}
                    <td class="method-info">
                        <br /> <br />
                        <h6 class="big">Shipping method:</h6>
                        <p>{{var order.shipping_description}}</p>
                    </td>
                    {{/depend}}
                    <td class="method-info">
                        <br /> <br />
                        <h6 class="big">Payment method:</h6>
                        {{var payment_html}}
                    </td>
                </tr>
            </table>
        </td>
    </tr>
</table>
<br /> <br />
{{var terms}}
{{depend show_signature}}
<br /><br /><br /><br />
Signature of renter: ________________________________  &nbsp;&nbsp;&nbsp; Date: ______________________________
<br /><br />
{{/depend}}
{{depend show_digitalsignature}}
<br /><br /><br /><br />
<table cellpadding="5" cellspacing="5" border="0">
    <tr><td width="150"><br /><br /><br /><br />Signature of renter: </td><td><img src="{{var digitalsignature}}" align="bottom"></td></tr>
        <tr><td>Date: </td><td>{{var date}}</td></tr></table>
<br /><br />
{{/depend}}
{{var footertext}}
</body></html>