<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head fieldset-legend head-account">Change Customer</h4>
    </div>

    <div class="fieldset" id="main1">
        <div class="hor-scroll"><?php echo $this->__('Change Customer:') ?>
            <?php echo ITwebexperts_Payperrentals_Block_Adminhtml_Sales_Order_Create_Changecustomer::getCustomersDropdown() ;?>
        </div>
    </div>
</div>