<div class="page-create-order">
<div class="switcher">
    <!--<div class="msg" style="color:red;font-size:10px;">If a rental product does not have "Use Times" enabled, it will not show time dropdown on configuration. If product is bundle or configurable it will use the config option setup to the main product not the subproducts</div>-->
    <div class="currency-switcher">
        <label for="currency_switcher"><?php echo Mage::helper('payperrentals')->__('Order Currency') . ':' ?></label>
        <select id="currency_switcher" name="order[currency]" onchange="order.setCurrencyId(this.value); order.setCurrencySymbol(this.options[this.selectedIndex].getAttribute('symbol'));">
            <?php foreach ($this->getAvailableCurrencies() as $_code): ?>
                <option value="<?php echo $_code ?>"<?php if ($_code == $this->getCurrentCurrencyCode()): ?> selected="selected"<?php endif; ?> symbol="<?php echo $this->getCurrencySymbol($_code) ?>"><?php echo $this->getCurrencyName($_code) ?></option>
            <?php endforeach; ?>
        </select>
    </div>

    <?php
        if(Mage::helper('payperrentals/config')->forceUseTimes()) {
            $_useTimes = Mage::helper('payperrentals')->useTimes(-1);
        }else{
            $_useTimes = 0;
        }
    ?>
    <?php $isAdminGlobal = true; ?>
    <div id="topDates" style="display: inline-block;margin-left: 10px;">
        <?php
        /** @var $block ITwebexperts_Payperrentals_Block_Adminhtml_Sales_Order_Create_Data */
        $block = new ITwebexperts_Payperrentals_Block_Adminhtml_Sales_Order_Create_Data();
        $templatePhpInitialisations = $block->getTemplatePhpInitialisations();
        $templateFunctions = $block->getTemplateFunctions();
        $templateGlobalCalendarFunctions = $block->getTemplateGlobalCalendarFunctions();
        $templateJsInitialisations = $block->getTemplateJsInitialisations();
        $templateStyles = $block->getTemplateStyles();
        $templateGlobalCalendar = $block->getTemplateGlobalCalendar();
        ?>

        <?php require($templatePhpInitialisations); ?>
        <?php require($templateJsInitialisations); ?>
        <?php require($templateGlobalCalendar); ?>
        <?php require($templateGlobalCalendarFunctions); ?>

            <button class="scalable change" id="changeButton" type="button" ><span><?php echo $this->__('Change All') ?></span></button>
        </div>
    </div>
</div>

<script type="text/javascript">order.setCurrencySymbol('<?php echo $this->getCurrencySymbol($this->getCurrentCurrencyCode()) ?>')</script>
<table cellspacing="0" width="100%">
    <tr>
        <?php if ($this->getCustomerId()): ?>
            <td class="side-col" style="background:none; padding:0;padding-right: 15px;">
                <div id="order-sidebar"><?php echo $this->getChildHtml('sidebar') ?></div>
            </td>
        <?php endif; ?>
        <td <?php if ($this->getCustomerId()): ?>class="main-col"<?php endif; ?>>
            <div id="order-additional_area" style="display:none" class="order-additional-area"><?php echo $this->getChildHtml('additional_area') ?></div>
            <div id="order-search" style="display:none" class="order-search-items"><?php echo $this->getChildHtml('search') ?></div>
            <div id="order-items"><?php echo $this->getChildHtml('items') ?></div>
            <div id="order-errors"><?php echo $this->getChildHtml('errors') ?></div>
            <div id="order-form_account">
                <?php echo $this->getChildHtml('change_customer') ?>
                <?php echo $this->getChildHtml('form_account') ?>
            </div>
            <?php if(!ITwebexperts_Payperrentals_Helper_Config::hideAdminAddresses()):?>
            <div id="order-addresses">
                <div id="order-billing_address" class="box-left"><?php echo $this->getChildHtml('billing_address') ?></div>
                <div id="order-shipping_address" class="box-right"><?php echo $this->getChildHtml('shipping_address') ?></div>
            </div>
            <?php endif;?>
            <div class="clear"></div>

            <div id="order-methods">
                <div id="order-billing_method" class="box-left payments"><?php echo $this->getChildHtml('billing_method') ?></div>
                <div id="order-shipping_method" class="box-right">
                    <?php echo $this->getChildHtml('shipping_method') ?>
                </div>
            </div>
            <div class="clear"></div>
            <div id="order-pickupdropoff" class="box-right">
                <div class="entry-edit">
                    <div class="entry-edit-head">
                        <h4 class="icon-head fieldset-legend head-account">Update Pickup Dropoff Dates</h4>
                    </div>

                    <div class="fieldset" id="main2">
                        <button style="margin-left: 10px;" id="buttonDropoff" type="button" name="buttonDropoff"><span><span>Update Dropoff and Pickup Dates</span></span></button>
                        <div style="" id="dialogDates">
                            <table cellspacing="0" class="form-list-s">
                                <tr><?php echo Mage::helper('payperrentals/dropoffpickup')->getDropoffInput($_storeOpen, $_storeClose, $_excludeHoursStart);?></tr>
                                <tr>
                                    <?php echo Mage::helper('payperrentals/dropoffpickup')->getPickupInput($_storeOpen, $_storeClose, $_excludeHoursEnd);?>
                                    <td class="button-column">
                                        <button style="margin-left: 10px;" id="okBut" type="button" name="okBut"><span><span>Ok</span></span></button>
                                    </td>
                                    <td class="button-column">
                                        <button style="margin-left: 10px;" id="cancelBut" type="button" name="cancelBut"><span><span>Cancel</span></span></button>
                                    </td>
                                </tr>
                            </table>
                        </div>
                        <p id="estimatedDates"></p>
                    </div>
                </div>
            </div>

            <?php if ($this->getChild('card_validation')): ?>
                <div class="clear"></div>
                <div id="order-methods">
                    <div id="order-card_validation" class="box-left payments"><?php echo $this->getChildHtml('card_validation') ?></div>
                </div>
            <?php endif; ?>

            <div class="clear"></div>
            <?php echo $this->getChildHtml('gift_options') ?>

            <div class="clear"></div>
            <div class="box-left entry-edit">
                <div class="entry-edit-head"><h4><?php echo Mage::helper('payperrentals')->__('Order History') ?></h4></div>
                <fieldset id="order-comment"><?php echo $this->getChildHtml('comment') ?></fieldset>
            </div>
            <div class="box-right entry-edit">
                <div class="entry-edit-head"><h4><?php echo Mage::helper('payperrentals')->__('Order Totals') ?></h4></div>
                <div id="order-totals" class="order-totals"><?php echo $this->getChildHtml('totals') ?></div>
            </div>
            <div class="clear"></div>
        </td>
    </tr>
</table>
</div>

<?php require($templateFunctions); ?>
<?php require($templateStyles); ?>
<script type="text/javascript">
    function onLoadActions(){
        $jppr('#sales_order_create_search_grid_table a[product_type="reservation"]').click(function () {
            $jppr(this).parent().parent().attr('is_pressed', '0');
        });

        $jppr('#sales_order_create_search_grid_table a[product_type!="reservation"]').each(function(){
            $jppr(this).parent().parent().attr('is_pressed', '0');
        });
    }

    AdminOrder.prototype.areasLoaded = AdminOrder.prototype.areasLoaded.wrap(function () {
        onLoadActions();

    });
    AdminOrder.prototype.itemsLoaded = AdminOrder.prototype.itemsLoaded.wrap(function () {
        onLoadActions();

    });

    onLoadActions();
</script>