<div class="entry-edit">
    <div class="entry-edit-head">
        <div id="quick-add-container" class="quick-add-container">
            <input type="text" name="find_product" class="find_product" placeholder="<?php echo $this->__('Name or SKU') ?>">
            <button class="scalable add" id="addButton" type="button" style="display: inline-block;"><span><?php echo $this->__('Quick Add Product') ?></span></button>
        </div>
        <div class="form-buttons"><?php echo $this->getButtonsHtml() ?></div>
    </div>
    <?php echo $this->getChildHtml() ?>
</div>


<script type="text/javascript">

    function getSerialNumbers(classValue, serviceUrl, params, selectCompleted){
        $jppr(classValue).each(function () {

            params['productId'] = $jppr(this).attr('prid');
            params['startDate'] = $jppr(this).attr('start_date');
            params['endDate'] = $jppr(this).attr('end_date');

            $jppr(this).autocomplete({
                serviceUrl: serviceUrl,
                type:'post',
                minChars: 0,
                paramName: 'value',
                params: params,
                onSelect: function (suggestion) {
                    if(typeof selectCompleted === 'function') {
                        selectCompleted($jppr(this).val());
                    }
                }
            });
        });
    }

    function selectCompleted(suggestion) {
        $jppr('#sales_order_create_search_grid_filter_name').val(suggestion);
        sales_order_create_search_gridJsObject.doFilter();
    }

    function loadAutocomplete() {
        var serviceUrl = '<?php echo Mage::getUrl("payperrentals_admin/adminhtml_ajax/getProducts/",array('form_key'=> Mage::getSingleton('core/session')->getFormKey()))?>';
        getSerialNumbers('.find_product', serviceUrl, {}, selectCompleted);
    }

    function onLoadActions(){
        loadAutocomplete();
        $jppr('#sales_order_create_search_grid_table a[product_type="reservation"]').click(function () {
            $jppr(this).parent().parent().attr('is_pressed', '0');
        });

        $jppr('#sales_order_create_search_grid_table a[product_type!="reservation"]').each(function(){
            $jppr(this).parent().parent().attr('is_pressed', '0');
        });
    }

    AdminOrder.prototype.areasLoaded = AdminOrder.prototype.areasLoaded.wrap(function () {
        onLoadActions();

    });
    AdminOrder.prototype.itemsLoaded = AdminOrder.prototype.itemsLoaded.wrap(function () {
        onLoadActions();

    });

    onLoadActions();


    $jppr('#addButton').click(function () {
        $jppr('#sales_order_create_search_grid_table tbody tr:first td .checkbox').attr('isadd', 1);
        $jppr('#sales_order_create_search_grid_table tbody tr:first td:first').click();
        return false;
    });
</script>