<script type="text/javascript" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS) .'itwebexperts_payperrentals/jquery/jquery-1.11.1.min.js'; ?>"></script>

<script type="text/javascript">
    $jppr = jQuery.noConflict();
</script>


<div class="content-header">
    <table cellspacing="0" class="grid-header">
        <tr>
            <td><h3><?php echo $this->__('Reservation History Table')?></h3></td>
        </tr>
    </table>
</div>

<div id="gridHtmlReservation">

</div>
<?php //echo Mage::app()->getFrontController()->getRequest()->getActionName(). '-'.Mage::app()->getFrontController()->getRequest()->getControllerName();?>

<script type="text/javascript">

    function getReservationGridHtml(){
        Element.show('loading-mask');

        $jppr.ajax({
            cache: false,
            dataType: 'json',
            type: 'post',
            url: '<?php echo Mage::getUrl("payperrentals_admin/adminhtml_ajax/getGridReservationCustomerHtml/",array('form_key'=> Mage::getSingleton('core/session')->getFormKey()))?>',
			data:'customer_id=<?php echo $this->getRequest()->getParam('id');?>',
            success: function (data) {
                Element.hide('loading-mask');
                $jppr('#gridHtmlReservation').html(data.html);

            }
        });
    }

    $jppr(document).ready(function() {
        getReservationGridHtml();

    });

</script>
<style type="text/css">


</style>