<?php if($this->getSource() instanceof Mage_Sales_Model_Order){ ?>
<?php if ((float) $this->getSource()->getDepositpprAmountRefunded()): ?>
    <tr>
        <td class="label"><strong><?php echo Mage::helper('payperrentals')->__('Deposit refunded to customer') ?></strong></td>
        <td><strong><?php echo $this->getSource()->getDepositpprAmountRefunded(); ?></strong></td>
    </tr>
<?php endif; ?>
<?php } else { ?>
<?php if ((float) $this->getSource()->getDepositpprAmount()): ?>
    <tr>
        <td class="label"><strong><?php echo Mage::helper('payperrentals')->__('Fee Refunded') ?></strong></td>
        <td><strong><?php echo $this->getSource()->getDepositpprAmount(); ?></strong></td>
    </tr>
<?php endif; 
}?>

