<script>
    function addDatePicker(){
        $jppr(".startdate, .enddate").datetimepicker({
            showOn: "both",
            buttonImage: "<?php echo ITwebexperts_Payperrentals_Helper_Html::getCalendarPopupImage(); ?>",
            buttonImageOnly: true,
            buttonText: "Select date",
            timeFormat: 'HH:mm:ss',
            stepHour: 1,
            stepMinute: 30,
            showSecond: false,
            showButtonPanel: false,
            dateFormat: 'yy-mm-dd'
        });

        $jppr('.repeattype').change(function(){
            if($jppr(this).val() == 'dayweek'){
                $jppr(this).parent().parent().next().show();
                valDateTo = $jppr(this).parent().parent().prev().find(".enddate").val();
                valDateFrom = $jppr(this).parent().parent().prev().prev().find(".startdate").val();
                $jppr(this).parent().parent().prev().find(".enddate").datetimepicker("option","timeOnly", true);
                $jppr(this).parent().parent().prev().prev().find(".startdate").datetimepicker("option","timeOnly", true);
                $jppr(this).parent().parent().prev().find(".enddate").val(valDateTo);
                $jppr(this).parent().parent().prev().prev().find(".startdate").val(valDateFrom);
            }else{
                $jppr(this).parent().parent().next().hide();
                $jppr(this).parent().parent().next().find('.repeatdays').val('');
                $jppr(this).parent().parent().prev().find(".enddate").datetimepicker("option","timeOnly", false);
                $jppr(this).parent().parent().prev().prev().find(".startdate").datetimepicker("option","timeOnly", false);            }
        });
        $jppr('.repeattype, .repeatdays').trigger('change');
        $jppr('.buttondelete').each(function(){
            var jButton = $jppr('<button type="button" title="Delete Fixed" style="margin-top:5px;margin-bottom:5px;" class="button btn-delete"><span><span>Delete Fixed</span></span></button>');
            $jppr('#registry_form'+$jppr(this).val()).append(jButton);
            $jppr(this).remove();
            var countForm = $jppr('.form-list').length;
        });
        $jppr('.btn-delete').click(function(){
           $jppr(this).parent().remove();
        });
    }
    $jppr(document).ready(function() {

        addDatePicker();

        var jButton = $jppr('<button type="button" title="Add new fixed date" style="margin-top:5px;margin-bottom:5px;" class="button btn-add-fixed"><span><span>Add fixed date</span></span></button>');
        jButton.insertBefore($jppr('#registry_form'));

        $jppr('.btn-add-fixed').click(function(){
            var clonedForm = $jppr('#registry_form1').clone();
            if( $jppr('#registry_form1').length  == 0){
                clonedForm = $jppr('#registry_form').clone();
                clonedForm.find('.name').parent().parent().remove();
            }

            var countForm = $jppr('.form-list').length;
            clonedForm.attr('id','registry_form'+countForm);
            while(true){
                if($jppr('input[name="start_date'+countForm+'"]').length > 0){
                    countForm++;
                }else{
                    break;
                }
            }
            clonedForm.find('.ui-datepicker-trigger').remove();
            clonedForm.find('.startdate').attr('name', 'start_date'+countForm).removeClass('hasDatepicker');
            clonedForm.find('.enddate').attr('name', 'end_date'+countForm).removeClass('hasDatepicker');
            clonedForm.find('.repeattype').attr('name', 'repeat_type'+countForm);
            clonedForm.find('.repeatdays').attr('name', 'repeat_days'+countForm);
            clonedForm.find('.startdate').attr('id', 'start_date'+countForm);
            clonedForm.find('.enddate').attr('id', 'end_date'+countForm);
            clonedForm.find('.repeattype').attr('id', 'repeat_type'+countForm);
            clonedForm.find('.repeatdays').attr('id', 'repeat_days'+countForm);
            $jppr('#edit_form').append(clonedForm);
            addDatePicker();
        });
    });
</script>