<style>
    .hor-scroll {
        overflow: visible;
    }

</style>
<script>
    $jppr(document).ready(function(){
        $jppr('.productdrop').chosen();
        /**
         * Checks form for errors
         */
        $jppr('button.save').attr('onClick','');
        $jppr('button.save').click(function(event){
            event.preventDefault();
            /**
             * Check that product ID is not blank
             */
            if($jppr('.productdrop').val() == -1){
                alert("Product must be selected");
                return false;
            }

            if($jppr('#frequency_quantity').val() == null || $jppr('#frequency_quantity').val() == 0){
                alert("Frequency quantity must be entered");
                return false;
            }

            if($jppr('#frequency_type').val() == -1){
                alert("Frequency type must be selected");
                return false;
            }

            if($jppr('#snippet_id').val() == -1){
                alert("Maintenance template must be selected");
                return false;
            }

            editForm.submit();

        });
    });
</script>