<style>
    .hor-scroll {
        overflow: visible;
    }
    #loader{
       position:absolute;
        display: none;
        z-index: 10;
    }
</style>
<div id="loader"><img src="<?php echo Mage::getDesign()->getSkinUrl('images/ajax-loader-tr.gif') ?>"></div>
<script>
    $jppr(document).ready(function() {
        $jppr('#loader').position({
            my: "center",
            at: "center",
            of: "#serials"
        });

        $jppr('.productdrop').chosen();

        if($jppr("#serials option").length == 0){
            $jppr("#serials").parent().parent().hide();
        }

        /**
         * Load maintenance templates to JS Object for applying
         */
        var templateJson = <?php echo Mage::helper('simaintenance')->templatesToJson()?>;
        var test = 'test';
        $jppr('#apply').click(function(e){
            e.preventDefault();
            var selectedId = $jppr('#snippet').val();
            $jppr('#summary').val(templateJson[selectedId].title);
            $jppr('#description').val(templateJson[selectedId].description);
        })
        hideDates();
        $jppr('#specific_dates').on("change",hideDates);
        $jppr('#product_id').on("change",loadSerials);
        /** Hide start & end date if specific dates is set to no */

        /**
         * Checks form for errors
         */
        $jppr('button.save').attr('onClick','');
        $jppr('button.save').click(function(event){
            event.preventDefault();
            /**
             * Check that product ID is not blank
             */
            if($jppr('.productdrop').val() == -1){
                alert("Product must be selected");
                return false;
            }

            if($jppr('#status').val() == -1){
                alert("Maintenance status must be selected");
                return false;
            }

            editForm.submit();

            });


    });
    function hideDates(event){
        if($jppr('#specific_dates').val() == 0) {
            $jppr('#start_date').parent().parent().css({"display": "none"});
            $jppr('#end_date').parent().parent().css({"display": "none"});
        } else {
            $jppr('#start_date').parent().parent().css({"display": "table-row"});
            $jppr('#end_date').parent().parent().css({"display": "table-row"});
        }
    }

    function showajax(){
        $jppr('#serials').prop( "disabled", true );
        $jppr('#loader').show();
        $jppr('#serials').css({backgroundColor:'#C2C2C2'});
        $jppr('#serials').animate({
           // backgroundColor:'#C2C2C2',
            opacity:.5
        });
    }

    function hideajax(){
        $jppr('#serials').css({backgroundColor:'#fff'});
        $jppr('#serials').animate({
            opacity:1
        });
        $jppr('#serials').prop( "disabled", false );
        $jppr('#loader').hide();
    }

    function hideshowserials(suggestions){
        if(suggestions.length == 0){
            $jppr("#serials").parent().parent().hide();
        } else{
            $jppr("#serials").parent().parent().show();
        }
    }

    function loadSerials(){
        showajax();
        var datatosend = 'productId=' + $jppr('.productdrop').val();
        $jppr.ajax({
            data: datatosend,
            cache: false,
            dataType: 'json',
            type: 'POST',
            url: '<?php echo Mage::getUrl("payperrentals_admin/adminhtml_ajax/getallserialsandstatus/",array('form_key'=> Mage::getSingleton('core/session')->getFormKey()));?>',
            success: function (data) {
                console.log(data);
                $jppr('#serials').empty();
                hideshowserials(data.suggestions);
                $jppr.each(data.suggestions, function(key,value){
                   $jppr('#serials').append($jppr('<option>').text(value.serial + ' - ' + value.status).attr('value',value.serial));
                });
                hideajax();
            }
        })
    }
</script>